import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {loadPlaywright} from './runtime.mjs';
const {_electron}=loadPlaywright(),root=path.resolve(import.meta.dirname,'../..'),packaged=process.argv.includes('--packaged');
const base=path.join(root,'build');fs.mkdirSync(base,{recursive:true});const profile=fs.mkdtempSync(path.join(base,'framework-smoke-'));
const executable=packaged?path.join(root,'build/program/RikeDesk-win32-x64/RikeDesk.exe'):path.join(root,'app/node_modules/electron/dist/electron.exe');
let app,page;const errors=[],checks=[];
async function launch(){app=await _electron.launch({executablePath:executable,args:[...(packaged?[]:[path.join(root,'app')]),`--verification-data=${profile}`,'--host-resolver-rules=MAP * ~NOTFOUND'],timeout:30000});page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));page.on('crash',()=>errors.push('renderer crash'));await page.locator('.season-grid').waitFor();await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.webContents.setAudioMuted(true);w.webContents.setBackgroundThrottling(false);w.hide();});}
async function nav(name){await page.getByRole('button',{name,exact:true}).click({force:true});}
try{
 await launch();const data=await page.evaluate(()=>window.learning.bootstrap());assert.equal(data.lessons.length,4);assert.equal(new Set(data.lessons.map(l=>l.season)).size,2);assert.ok(!data.lessons.some(l=>l.id.startsWith('S01E')));assert.equal((await page.evaluate(()=>window.learning.diagnostics())).dataDirectory,profile);checks.push('generic library and isolated profile');
 assert.ok((await page.evaluate(()=>window.learning.lesson('demo-intro'))).markdown.length>100);await page.getByRole('button',{name:'开始阅读',exact:true}).click({force:true});await page.locator('.article').waitFor();await page.getByRole('button',{name:'播放音频',exact:true}).click({force:true});await page.waitForFunction(()=>{const a=document.querySelector('audio');return a&&!a.paused&&a.currentTime>.2;});
 const start=await page.locator('audio').evaluate(a=>a.currentTime);for(const name of ['课程书架','我的笔记','学习计划','间隔复习','阅读偏好','全文搜索']){await nav(name);assert.equal(await page.locator('audio').evaluate(a=>a.paused),false);}assert.ok(await page.locator('audio').evaluate(a=>a.currentTime)>start);checks.push('continuous audio across six pages');
 await nav('课程书架');await page.getByRole('button',{name:'打开 demo-text',exact:true}).click({force:true});await page.waitForFunction(()=>document.querySelector('.article h1')?.textContent==='仅文稿课程');assert.equal(await page.locator('audio').getAttribute('data-lesson-id'),'demo-intro');assert.equal(await page.locator('audio').evaluate(a=>a.paused),false);assert.ok((await page.locator('.article').innerText()).includes('没有对应音频'));checks.push('independent reading and playback');
 await page.getByRole('textbox',{name:'课程笔记',exact:true}).fill('框架原生窗口回归：我的学习行动。');await nav('我的笔记');assert.equal((await page.evaluate(()=>window.learning.note('demo-text'))).content,'框架原生窗口回归：我的学习行动。');checks.push('note flush on navigation');
 await nav('课程书架');await page.getByRole('button',{name:'播放 demo-audio',exact:true}).click({force:true});await page.waitForFunction(()=>{const a=document.querySelector('audio');return a?.dataset.lessonId==='demo-audio'&&!a.paused&&a.currentTime>.2;});assert.equal(await page.locator('audio').count(),1);await page.evaluate(()=>window.learning.automaticBackup());assert.equal(await page.locator('audio').evaluate(a=>a.paused),false);checks.push('audio-only playback and backup');
 await nav('全文搜索');await page.getByRole('textbox',{name:'搜索标题正文和笔记'}).fill('框架');await page.waitForFunction(()=>document.querySelectorAll('[data-search-id]').length>0);assert.ok(await page.locator('[data-search-id]').count()>0);checks.push('Chinese full-text search');
 await nav('学习计划');await page.getByRole('button',{name:'创建学习计划',exact:true}).click({force:true});await page.getByRole('textbox',{name:'计划名称',exact:true}).fill('通用框架计划');await page.getByRole('combobox',{name:'选择计划分组'}).selectOption(String(data.lessons.find(l=>l.id==='demo-advanced').season));await page.getByRole('checkbox',{name:'选择课程 demo-advanced',exact:true}).check();await page.getByRole('button',{name:'保存学习计划',exact:true}).click({force:true});await page.waitForFunction(()=>document.querySelectorAll('[data-plan-id]').length===1);checks.push('dynamic group selection in plans');
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1024,768));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('small-window layout');
 await app.close();app=null;await launch();assert.equal((await page.evaluate(()=>window.learning.note('demo-text'))).content,'框架原生窗口回归：我的学习行动。');assert.equal((await page.evaluate(()=>window.learning.studyData())).plans[0].name,'通用框架计划');assert.deepEqual(errors,[]);checks.push('restart retains learning data');await app.close();app=null;
 const resolved=fs.realpathSync(profile);assert.equal(path.dirname(resolved),fs.realpathSync(base));assert.ok(path.basename(resolved).startsWith('framework-smoke-'));fs.rmSync(resolved,{recursive:true,maxRetries:3,retryDelay:500});console.log(JSON.stringify({passed:true,mode:packaged?'packaged':'development',checks}));
}finally{if(app)await app.close();}
