import {useEffect,useState} from 'react';
import {Bookmark as BookmarkIcon,Headphones,Highlighter,NotebookPen,X} from 'lucide-react';
import type {Annotation,Bookmark,CardDraft,Detail,SelectionBlock,Source} from './types';
import {formatTime} from './common';
import {useSessionState} from './session';
import CardDialog from './CardDialog';
function rangeFromOffsets(element:Element,start:number,end:number){
  const walker=document.createTreeWalker(element,NodeFilter.SHOW_TEXT);let node:Node|null,position=0,startNode:Node|null=null,endNode:Node|null=null,startOffset=0,endOffset=0;
  while((node=walker.nextNode())){const length=node.textContent?.length||0;if(!startNode&&start>=position&&start<=position+length){startNode=node;startOffset=start-position;}if(end>=position&&end<=position+length){endNode=node;endOffset=end-position;break;}position+=length;}
  if(!startNode||!endNode)return null;const range=document.createRange();range.setStart(startNode,startOffset);range.setEnd(endNode,endOffset);return range;
}
function findQuote(element:Element,quote:string,preferred:number){const text=element.textContent||'',positions=[];let start=text.indexOf(quote);while(start>=0){positions.push(start);start=text.indexOf(quote,start+1);}if(positions.length){positions.sort((a,b)=>Math.abs(a-preferred)-Math.abs(b-preferred));return rangeFromOffsets(element,positions[0],positions[0]+quote.length);}const indexes:number[]=[],characters:string[]=[];for(let i=0;i<text.length;i++)if(!/\s/.test(text[i])){characters.push(text[i]);indexes.push(i);}const normalized=quote.replace(/\s/g,''),match=characters.join('').indexOf(normalized);return normalized&&match>=0?rangeFromOffsets(element,indexes[match],indexes[match+normalized.length-1]+1):null;}
function selectedBlocks(detail:Detail):SelectionBlock[]{
  const selection=window.getSelection();if(!selection?.rangeCount||selection.isCollapsed)return [];const range=selection.getRangeAt(0),result:SelectionBlock[]=[];
  for(const element of document.querySelectorAll<HTMLElement>('.markdown [data-block-id]')){
    if(!range.intersectsNode(element))continue;const block=document.createRange();block.selectNodeContents(element);const part=range.cloneRange();if(part.compareBoundaryPoints(Range.START_TO_START,block)<0)part.setStart(element,0);if(part.compareBoundaryPoints(Range.END_TO_END,block)>0)part.setEnd(element,element.childNodes.length);
    const value=part.toString();if(!value.trim())continue;const prefix=document.createRange();prefix.selectNodeContents(element);prefix.setEnd(part.startContainer,part.startOffset);const start=prefix.toString().length+(value.length-value.trimStart().length),quote=value.trim(),end=start+quote.length,text=element.textContent||'';
    result.push({lessonId:detail.id,blockId:element.dataset.blockId!,quote,start,end,prefix:text.slice(Math.max(0,start-60),start),suffix:text.slice(end,end+60),color:'yellow',comment:''});
  }return result;
}
function AnnotationItem({annotation,onOpen,onRefresh,onCard,onReanchor,onMessage,onRemove,detail}:{annotation:Annotation;onOpen:()=>void;onRefresh:()=>void;onCard:(draft:CardDraft)=>void;onReanchor:()=>void;onMessage:(message:string)=>void;onRemove:()=>void;detail:Detail}){
  const [comment,setComment]=useState(annotation.comment),[color,setColor]=useState(annotation.color);
  return <article data-annotation-id={annotation.id} className={'annotation-item '+annotation.anchor_state}><button className="annotation-quote" onClick={onOpen}>{annotation.quote}</button>{annotation.anchor_state!=='anchored'&&<p>{annotation.anchor_reason||'原文段落变更，已按摘录重新定位。'}</p>}<textarea aria-label={`批注 ${annotation.id}`} placeholder="我的批注" value={comment} maxLength={10000} onChange={e=>setComment(e.target.value)}/><div><select aria-label={`划线颜色 ${annotation.id}`} value={color} onChange={e=>setColor(e.target.value as Annotation['color'])}><option value="yellow">暖黄</option><option value="green">绿色</option><option value="blue">蓝色</option></select><button onClick={async()=>{try{await window.learning.editAnnotation(annotation.id,comment,color);onRefresh();onMessage('批注已保存。');}catch{onMessage('批注尚未保存，请重试。');}}}>保存批注</button><button onClick={onRemove}>移除</button></div><div>{annotation.anchor_state==='orphaned'&&<button onClick={onReanchor}>重新关联</button>}<button onClick={async()=>{try{await window.learning.editNote({kind:'excerpt',title:(detail.title+' · 摘录').slice(0,200),content:comment,tags:[],sourceLesson:detail.id,sourceBlock:annotation.resolved_block_id,sourceQuote:annotation.quote});onMessage('已保存为摘录笔记，可在我的笔记中查看。');}catch{onMessage('摘录笔记未能保存。');}}}>保存为摘录笔记</button><button onClick={()=>onCard({question:detail.title+'：这个观点说明了什么？',answer:comment||annotation.quote,lessonId:detail.id,blockId:annotation.resolved_block_id,annotationId:annotation.id,sourceQuote:annotation.quote})}>创建复习卡</button></div></article>;
}
export default function AnnotationTools({detail,currentBlock,audioPosition,onSource}:{detail:Detail|null;currentBlock:()=>string|null;audioPosition:()=>number;onSource:(source:Source)=>void}){
  const [annotations,setAnnotations]=useState<Annotation[]>([]),[bookmarks,setBookmarks]=useState<Bookmark[]>([]),[selection,setSelection]=useState<SelectionBlock[]>([]),[comment,setComment]=useState(''),[color,setColor]=useState<Annotation['color']>('yellow'),[open,setOpen]=useState(false),[message,setMessage]=useState(''),[card,setCard]=useState<CardDraft|null>(null),[reanchor,setReanchor]=useState<string|null>(null);
  const [removed,setRemoved]=useState<Annotation[]>([]),[undo,setUndo]=useSessionState<string|null>('annotations.undo',null);
  async function refresh(){if(!detail)return;const [a,b,c]=await Promise.all([window.learning.annotations(detail.id),window.learning.bookmarks(detail.id),window.learning.annotations(detail.id,true)]);setAnnotations(a);setBookmarks(b);setRemoved(c);}
  async function recover(id:string){try{await window.learning.trashAnnotation(id,true);if(undo===id)setUndo(null);await refresh();setMessage('划线和批注已恢复。');}catch{setMessage('划线未能恢复，请重试。');}}
  useEffect(()=>{setSelection([]);setMessage('');setOpen(false);setReanchor(null);let alive=true;if(detail)Promise.all([window.learning.annotations(detail.id),window.learning.bookmarks(detail.id),window.learning.annotations(detail.id,true)]).then(([a,b,c])=>{if(alive){setAnnotations(a);setBookmarks(b);setRemoved(c);}}).catch(()=>{if(alive)setMessage('划线与书签暂时无法读取。');});return()=>{alive=false;};},[detail?.id]);
  useEffect(()=>{const select=()=>{if(!detail)return;const selected=selectedBlocks(detail);if(selected.length)setSelection(selected);};document.addEventListener('mouseup',select);document.addEventListener('keyup',select);return()=>{document.removeEventListener('mouseup',select);document.removeEventListener('keyup',select);};},[detail?.id]);
  useEffect(()=>{if(!CSS.highlights)return;const colors={yellow:[] as Range[],green:[] as Range[],blue:[] as Range[]};for(const a of annotations){if(!a.resolved_block_id)continue;const element=document.querySelector(`[data-block-id="${a.resolved_block_id}"]`),range=element?findQuote(element,a.quote,a.start_offset):null;if(range)colors[a.color].push(range);}for(const name of ['yellow','green','blue'] as const)CSS.highlights.set('annotation-'+name,new Highlight(...colors[name]));return()=>{for(const name of ['yellow','green','blue'])CSS.highlights.delete('annotation-'+name);};},[annotations,detail?.id]);
  async function saveSelection(){if(!selection.length)return;try{if(reanchor){if(selection.length!==1){setMessage('重新关联时请选择一个段落中的文字。');return;}await window.learning.reanchorAnnotation(reanchor,selection[0]);setReanchor(null);}else await window.learning.addAnnotations(selection.map(s=>({...s,color,comment})));setSelection([]);setComment('');window.getSelection()?.removeAllRanges();await refresh();setMessage('划线与批注已保存。');}catch{setMessage('划线未能保存，请重新选择正文中的文字。');}}
  async function bookmark(kind:Bookmark['kind']){if(!detail)return;try{const blockId=currentBlock();if(kind==='paragraph'&&!blockId)return;await window.learning.addBookmark({lessonId:detail.id,kind,blockId:kind==='paragraph'?blockId:null,position:kind==='audio'?audioPosition():null,label:kind==='audio'?`${detail.title} · ${formatTime(audioPosition())}`:(detail.blocks.find(b=>b.id===blockId)?.text.slice(0,90)||detail.title)});await refresh();setMessage('书签已保存，可以从摘录与书签中回跳。');}catch{setMessage('书签未能保存，请重试。');}}
  const notice=message&&<div role="status" className="annotation-message">{message}{undo&&removed.some(a=>a.id===undo)&&<button onClick={()=>void recover(undo)}>撤销移除</button>}<button aria-label="关闭摘录提示" onClick={()=>setMessage('')}><X size={13}/></button></div>;
  if(!detail)return null;
  return <><div className="annotation-toolbar"><span><Highlighter size={15}/>选中文字，划线并记下理解</span><div><button aria-label="添加段落书签" onClick={()=>void bookmark('paragraph')}><BookmarkIcon size={16}/></button><button aria-label="添加音频书签" disabled={!detail.audio} onClick={()=>void bookmark('audio')}><Headphones size={16}/></button><button className={open?'active':''} onClick={()=>setOpen(!open)}><NotebookPen size={16}/>摘录与书签 {annotations.length+bookmarks.length}</button></div></div>{selection.length>0&&<div className="selection-actions"><strong>{reanchor?'重新关联划线':'已选择 '+selection.length+' 个段落'}</strong><select aria-label="新划线颜色" value={color} onChange={e=>setColor(e.target.value as Annotation['color'])}><option value="yellow">暖黄</option><option value="green">绿色</option><option value="blue">蓝色</option></select><input aria-label="选区批注" placeholder="写一点自己的理解（可选）" value={comment} maxLength={10000} onChange={e=>setComment(e.target.value)}/><button className="secondary-button" onMouseDown={e=>e.preventDefault()} onClick={()=>void saveSelection()}>{reanchor?'保存关联':'保存划线'}</button><button aria-label="取消选区" onClick={()=>{setSelection([]);setReanchor(null);}}><X size={16}/></button></div>}{!open&&notice}{open&&<section className="annotation-panel"><header><strong>摘录与书签</strong><button aria-label="关闭摘录与书签" onClick={()=>setOpen(false)}><X size={17}/></button></header>{notice}<h3>划线与批注</h3>{annotations.map(a=><AnnotationItem key={a.id} annotation={a} detail={detail} onOpen={()=>{if(a.resolved_block_id)onSource({lessonId:detail.id,blockId:a.resolved_block_id});else setMessage(a.anchor_reason||'请选择新的文字重新关联。');}} onRefresh={()=>void refresh()} onRemove={()=>{void window.learning.trashAnnotation(a.id).then(async()=>{setUndo(a.id);await refresh();setMessage('划线已移除，可撤销或从已移除划线中恢复。');}).catch(()=>setMessage('划线未能移除，请重试。'));}} onCard={setCard} onMessage={setMessage} onReanchor={()=>{setReanchor(a.id);setOpen(false);setMessage('请在本讲正文中选择新的文字，保存关联。');}}/>)}{!annotations.length&&<p>选择正文中的文字后保存划线。</p>}{removed.length>0&&<details className="removed-items"><summary>已移除划线 {removed.length}</summary>{removed.map(a=><div key={a.id} data-removed-annotation-id={a.id}><span>{a.quote}</span><button onClick={()=>void recover(a.id)}>恢复划线</button></div>)}</details>}<h3>段落与音频书签</h3>{bookmarks.map(b=><article className="bookmark-item" key={b.id} data-bookmark-id={b.id}><button onClick={()=>onSource({lessonId:b.lesson_id,blockId:b.block_id,audioPosition:b.audio_position})}><strong>{b.kind==='audio'?'音频 '+formatTime(b.audio_position||0):'段落书签'}</strong><span>{b.label}</span></button><button aria-label={`删除书签 ${b.id}`} onClick={async()=>{await window.learning.removeBookmark(b.id);await refresh();}}>移除</button></article>)}{!bookmarks.length&&<p>保存当前阅读段落或音频时点，下次可以回到这里。</p>}</section>}{card&&<CardDialog draft={card} onClose={()=>setCard(null)} onSaved={()=>setMessage('复习卡已创建。')}/>}</>;
}
