import {useEffect,useState} from 'react';
import {Download,FolderOpen,RotateCcw,ShieldCheck} from 'lucide-react';
import Modal from './Modal';
import type {BackupStatus} from './types';
import {failureMessage} from './common';
export default function BackupPanel({onPrepare}:{onPrepare:()=>Promise<void>}){
  const [status,setStatus]=useState<BackupStatus|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[restoreOpen,setRestoreOpen]=useState(false);
  const refresh=()=>void window.learning.backupStatus().then(setStatus).catch(()=>setMessage('备份目录暂时无法读取。'));useEffect(refresh,[]);
  async function manual(){setBusy(true);try{await onPrepare();const result=await window.learning.backupNow();setMessage(result?'个人数据和图片附件已备份到所选位置。':'已取消备份。');refresh();}catch(error){setMessage(failureMessage(error));}finally{setBusy(false);}}
  async function restore(){setRestoreOpen(false);setBusy(true);try{await onPrepare();const result=await window.learning.restoreBackup();setMessage(result?'恢复完成，正在重新打开个人学习空间。':'已取消恢复，当前数据未改动。');}catch{setMessage('所选备份无法恢复，请检查备份文件和软件版本。当前数据未改动。');}finally{setBusy(false);refresh();}}
  return <section className="backup-panel"><div className="section-title"><div><h2><ShieldCheck size={20}/>个人数据备份</h2><p>备份笔记、划线、书签、计划、复习和进度，以及个人图片附件；不重复备份课程资料。</p></div></div><div className="backup-actions"><button className="secondary-button" disabled={busy} onClick={()=>void manual()}><Download size={17}/>手动备份</button><button className="secondary-button" disabled={busy} onClick={()=>setRestoreOpen(true)}><RotateCcw size={17}/>恢复备份</button><button className="text-button" disabled={busy} onClick={()=>void window.learning.openBackupFolder().catch(()=>setMessage('无法打开备份目录。'))}><FolderOpen size={17}/>打开本机备份目录</button></div><label className="automatic-backup"><input type="checkbox" aria-label="开启自动备份" checked={status?.enabled??true} disabled={busy} onChange={async e=>{try{await window.learning.setSetting('autoBackup',e.target.checked);refresh();}catch{setMessage('自动备份设置未保存，请重试。');}}}/>开启自动备份：启动后和运行期间每 30 分钟保存一致性快照，保留最近 7 份自动备份。</label><button className="text-button" disabled={busy} onClick={async()=>{setBusy(true);try{await onPrepare();const result=await window.learning.automaticBackup();setMessage(result?'自动备份已更新。':'自动备份已关闭或正在执行。');refresh();}catch{setMessage('自动备份未完成，请重试。');}finally{setBusy(false);}}}>立即更新自动备份</button>{message&&<p role="status" className="backup-message">{message}</p>}{status&&<div className="backup-list"><strong>本机可恢复快照</strong>{status.files.length?status.files.slice(0,10).map(file=><div key={file.name}><span>{file.name}</span><small>{(file.bytes/1024).toFixed(0)} KB</small></div>):<p>尚无自动或恢复前备份。也可以选择自己保存的备份文件恢复。</p>}</div>}{restoreOpen&&<Modal label="恢复个人学习数据" onClose={()=>setRestoreOpen(false)}>{close=><div className="learning-dialog restore-dialog"><h2>恢复个人学习数据</h2><p>恢复会用备份中的个人数据替换当前数据。软件会先验证格式、版本、完整性和附件，再备份当前数据；失败时保留当前学习记录。</p><p>有效恢复完成后会重新打开软件界面，课程资料继续使用。</p><footer><button className="secondary-button" onClick={close}>取消恢复</button><button className="primary-button" onClick={()=>void restore()}>选择备份并恢复</button></footer></div>}</Modal>}</section>;
}
