import {useEffect,useRef,useState} from 'react';
import {Download,FileText,ImagePlus,NotebookPen,Plus,RotateCcw,Search,Trash2} from 'lucide-react';
import type {Asset,CardDraft,Lesson,Note,Source} from './types';
import {flushNotes,pendingNoteFlush} from './common';
import {useSessionState,useScrollMemory,noteCarets} from './session';
import CardDialog from './CardDialog';
function DraftEditor({note,onSaved,onSource,onReview,onTrash,onMessage}:{note:Note;onSaved:()=>void;onSource:(source:Source)=>void;onReview:(draft:CardDraft)=>void;onTrash:()=>void;onMessage:(text:string)=>void}){
  const [title,setTitle]=useState(note.title),[content,setContent]=useState(note.content),[labels,setLabels]=useState(note.tags.join('，')),[state,setState]=useState('已保存'),[assets,setAssets]=useState<Asset[]>([]);
  const editor=useScrollMemory<HTMLElement>('note.editor.'+note.id);
  useEffect(()=>{const saved=noteCarets.get(note.id);if(saved){const input=editor.current?.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[aria-label="${saved.field}"]`);if(input){input.focus({preventScroll:true});input.setSelectionRange(saved.start,saved.end);input.scrollTop=saved.scroll;}}},[note.id]);
  function remember(event:React.SyntheticEvent){const input=event.target;if(input instanceof HTMLInputElement||input instanceof HTMLTextAreaElement)noteCarets.set(note.id,{field:input.getAttribute('aria-label')||'',start:input.selectionStart||0,end:input.selectionEnd||0,scroll:input.scrollTop});}
  const draft=useRef({title:note.title,content:note.content,tags:note.tags,revision:0,saved:0}),timer=useRef<ReturnType<typeof setTimeout>|null>(null),saving=useRef<Promise<void>|null>(null),mounted=useRef(true);
  async function persist():Promise<void>{if(saving.current){await saving.current;if(draft.current.revision>draft.current.saved)return persist();return;}if(draft.current.revision===draft.current.saved)return;const current={...draft.current};const promise=(async()=>{try{await window.learning.editNote({id:note.id,kind:note.kind,title:current.title.trim()||'未命名笔记',content:current.content,tags:current.tags});draft.current.saved=current.revision;if(mounted.current&&current.revision===draft.current.revision)setState('已保存');onSaved();}catch(error){if(mounted.current)setState('保存失败，请重试');throw error;}})();saving.current=promise;try{await promise;}finally{saving.current=null;}if(draft.current.revision>draft.current.saved)await persist();}
  useEffect(()=>{mounted.current=true;pendingNoteFlush.add(persist);void window.learning.assets(note.id).then(setAssets);return()=>{mounted.current=false;if(timer.current)clearTimeout(timer.current);void persist().catch(()=>{}).finally(()=>{if(!mounted.current)pendingNoteFlush.delete(persist);});};},[note.id]);
  function update(values:Partial<typeof draft.current>){Object.assign(draft.current,values);draft.current.revision++;setState('正在保存…');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void persist().catch(()=>{}),500);}
  const source:Source={lessonId:note.lesson_id||note.source_lesson||undefined,blockId:note.source_block,noteId:note.id,sourceQuote:note.source_quote};
  async function attach(){try{await persist();const result=await window.learning.importAsset({noteId:note.id});if(result)setAssets(await window.learning.assets(note.id));}catch{onMessage('图片未能添加，请检查格式和大小。');}}
  async function exportNote(format:'markdown'|'pdf'){try{await persist();const result=await window.learning.exportNotes({format,noteIds:[note.id]});if(result)onMessage('已导出到所选位置。');}catch{onMessage('导出未完成，请重试。');}}
  return <section ref={editor} onSelectCapture={remember} onBlurCapture={remember} onKeyUpCapture={remember} onScrollCapture={remember} className="personal-editor"><div className="personal-editor-tools"><span className={state.includes('失败')?'save-error':'save-state'}>{state}</span><button aria-label="添加笔记图片" title="添加图片，最多 25 MB" onClick={()=>void attach()}><ImagePlus size={17}/></button><button aria-label="删除这篇笔记" onClick={async()=>{await persist();onTrash();}}><Trash2 size={17}/></button></div><input className="note-title-input" aria-label="笔记标题" placeholder="笔记标题" maxLength={200} value={title} onChange={e=>{setTitle(e.target.value);update({title:e.target.value});}}/><input className="note-tags-input" aria-label="笔记标签" placeholder="添加标签，用逗号分隔，最多 20 个" value={labels} onChange={e=>{setLabels(e.target.value);update({tags:e.target.value.split(/[,，]/).map(s=>s.trim()).filter(Boolean)});}}/>{source.lessonId&&<button className="note-source" onClick={()=>onSource(source)}>回到课程出处 · {source.lessonId}{source.blockId?' · 正文段落':''}</button>}{note.source_quote&&<blockquote className="note-excerpt">{note.source_quote}</blockquote>}<textarea className="personal-note-content" aria-label="笔记正文" placeholder="写下自己的理解…" maxLength={200000} value={content} onChange={e=>{setContent(e.target.value);update({content:e.target.value});}} onBlur={()=>void persist().catch(()=>{})}/>{assets.length>0&&<div className="personal-assets">{assets.map(asset=><div key={asset.id}><img src={asset.url} alt={asset.name}/><span>{asset.name}</span><button aria-label={`移除图片 ${asset.id}`} onClick={async()=>{await window.learning.removeAsset(asset.id);setAssets(await window.learning.assets(note.id));}}>移除</button></div>)}</div>}<footer><div><button className="text-button" onClick={()=>void exportNote('markdown')}>导出这篇 Markdown</button><button className="text-button" onClick={()=>void exportNote('pdf')}>导出这篇 PDF</button></div><button className="secondary-button" onClick={async()=>{await persist();onReview({...source,question:title||'如何用自己的话解释这个想法？',answer:content});}}>为笔记创建复习卡</button></footer>{state.includes('失败')&&<button className="text-button" onClick={()=>void persist().catch(()=>{})}>重试保存</button>}</section>;
}
export default function NoteWorkspace({lessons,onSource,selectedNote,onConsumed,onChanged}:{lessons:Lesson[];onSource:(source:Source)=>void;selectedNote:string|null;onConsumed:()=>void;onChanged:()=>void}){
  const [notes,setNotes]=useState<Note[]>([]),[selected,setSelected]=useSessionState<string|null>('notes.selected',selectedNote),[tab,setTab]=useSessionState('notes.tab','all'),[query,setQuery]=useSessionState('notes.query',''),[tag,setTag]=useSessionState('notes.tag',''),[message,setMessage]=useState(''),[card,setCard]=useState<CardDraft|null>(null);
  const list=useScrollMemory<HTMLElement>('notes.list',notes.length>0);
  const lessonMap=new Map(lessons.map(l=>[l.id,l]));
  async function refresh(){try{setNotes(await window.learning.allNotes(tab==='trash'));onChanged();}catch{setMessage('笔记暂时无法读取。');}}
  useEffect(()=>{void refresh();},[tab]);useEffect(()=>{if(selectedNote){setSelected(selectedNote);setTab('all');setQuery('');setTag('');onConsumed();}},[selectedNote]);
  const title=(n:Note)=>n.title||lessonMap.get(n.lesson_id||n.source_lesson||'')?.title||'课程笔记';
  const filtered=notes.filter(n=>(['all','trash'].includes(tab)||n.kind===tab)&&(!tag||n.tags.includes(tag))&&`${title(n)} ${n.content} ${n.source_quote} ${n.tags.join(' ')}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const chosen=notes.find(n=>n.id===selected),availableTags=[...new Set(notes.flatMap(n=>n.tags))].sort();
  async function create(){try{await flushNotes();const result=await window.learning.editNote({kind:'free',title:'新的想法',content:'',tags:[]});setTab('all');setSelected(result.id);setNotes(await window.learning.allNotes());onChanged();}catch{setMessage('新笔记未能创建，请重试。');}}
  async function exportAll(format:'markdown'|'pdf'){try{await flushNotes();const result=await window.learning.exportNotes({format});if(result)setMessage(`已导出 ${result.entries} 项笔记与摘录。`);}catch{setMessage('暂无可导出内容，或导出未完成。');}}
  return <main className="note-workspace"><header className="workspace-heading"><div><div className="eyebrow">MY IDEAS</div><h1>我的笔记</h1><p>笔记、摘录与出处，留在自己的学习空间。</p></div><div><button className="secondary-button" onClick={()=>void exportAll('markdown')}><Download size={16}/>导出 Markdown</button><button className="secondary-button" onClick={()=>void exportAll('pdf')}><Download size={16}/>导出 PDF</button><button className="primary-button" onClick={()=>void create()}><Plus size={17}/>新建独立笔记</button></div></header>{message&&<div role="status" className="inline-message">{message}<button onClick={()=>setMessage('')}>关闭</button></div>}<div className="notebook-filters"><div>{[['all','全部'],['course','课程笔记'],['free','独立笔记'],['excerpt','摘录'],['trash','回收站']].map(([id,name])=><button key={id} className={tab===id?'active':''} onClick={async()=>{await flushNotes();setTab(id);setSelected(null);}}>{name}</button>)}</div><label><Search size={16}/><input aria-label="搜索全部个人笔记" placeholder="搜笔记、摘录和标签" value={query} maxLength={100} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="按笔记标签筛选" value={tag} onChange={e=>setTag(e.target.value)}><option value="">全部标签</option>{availableTags.map(t=><option key={t}>{t}</option>)}</select></div><div className="notebook-columns"><aside ref={list} className="personal-note-list"><small>{filtered.length} 篇笔记</small>{filtered.map(n=><button key={n.id} data-note-id={n.id} className={n.id===selected?'active':''} onClick={async()=>{await flushNotes();setSelected(n.id);}}><span>{n.kind==='course'?<FileText size={15}/>:<NotebookPen size={15}/>} {n.kind==='course'?'课程笔记':n.kind==='excerpt'?'摘录':'独立笔记'}</span><strong>{title(n)}</strong><p>{n.content||n.source_quote||'开始写下自己的理解'}</p><div>{n.tags.map(t=><em key={t}>{t}</em>)}</div><small>{new Date(n.updated_at).toLocaleDateString('zh-CN')}</small></button>)}{!filtered.length&&<p className="list-empty">{tab==='trash'?'回收站是空的。':'这里还没有笔记。可以先新建，或到课程中记下想法。'}</p>}</aside>{chosen?tab==='trash'?<section className="personal-editor trash-preview"><h2>{title(chosen)}</h2><p>删除的笔记保留在回收站中，恢复后仍关联原课程和图片。</p><blockquote>{chosen.content}</blockquote><button className="primary-button" onClick={async()=>{await window.learning.trashNote(chosen.id,true);setSelected(null);await refresh();setMessage('笔记已恢复，可在全部笔记中查看。');}}><RotateCcw size={17}/>恢复笔记</button></section>:<DraftEditor key={chosen.id} note={chosen} onSaved={()=>void refresh()} onSource={onSource} onReview={setCard} onMessage={setMessage} onTrash={()=>{void window.learning.trashNote(chosen.id).then(()=>{setSelected(null);void refresh();setMessage('笔记已移入回收站。');});}}/>:<section className="personal-editor notebook-placeholder"><NotebookPen size={44}/><h2>给一个想法，留一点空间。</h2><p>选一篇笔记，或开始新的记录。<br/>修改会自动保存在本机。</p></section>}</div>{card&&<CardDialog draft={card} onClose={()=>setCard(null)} onSaved={()=>setMessage('复习卡已创建，到期后可在间隔复习中查看。')}/>}</main>;
}
