import {forwardRef,useEffect,useImperativeHandle,useLayoutEffect,useRef,useState} from 'react';
import {ArrowLeft,BookOpen,CheckCircle2,ChevronDown,ChevronLeft,ChevronRight,FileText,Headphones,Play,Pause,Maximize2,NotebookPen,Search,Star,X} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type {Detail,Flag,Lesson,Preferences,Source} from './types';
import AnnotationTools from './AnnotationTools';
import NoteEditor from './NoteEditor';
import Status from './Status';
export type ReadingPosition={scroll:number;anchor:string|null;offset:number};
export type ReaderHandle={capture():ReadingPosition|null;find():void};
export type Jump={serial:number;id:string;blockId:string|null;query:string;source:'title'|'body'|'notes'};
type Props={onPlay:()=>void;isPlaying:boolean;lesson:Lesson;detail:Detail|null;error:string;directory:Lesson[];noteOpen:boolean;onNoteOpen:(value:boolean)=>void;collapsed:boolean;onFocus:()=>void;backLabel?:string;onBack:()=>void;onOpen:(id:string)=>void;onSaved:()=>void;flag:Flag|undefined;onFlag:(key:'favorite'|'finished',value:boolean)=>void;preferences:Preferences;onPreferences:(value:Partial<Preferences>)=>void;position:()=>ReadingPosition|null;onRead:(id:string,position:ReadingPosition)=>void;jump:Jump|null;onAddQueue:()=>void;audioPosition:()=>number;onSource:(source:Source)=>void};
const Reader=forwardRef<ReaderHandle,Props>(function Reader(props,ref){
  const {lesson,detail,noteOpen,preferences,jump}=props;
  const scroll=useRef<HTMLDivElement>(null),restoring=useRef(false),findInput=useRef<HTMLInputElement>(null),lastJump=useRef(0);
  const [referenceOpen,setReferenceOpen]=useState(false),[findOpen,setFindOpen]=useState(false),[findQuery,setFindQuery]=useState(''),[matchIndex,setMatchIndex]=useState(0),[focusedBlock,setFocusedBlock]=useState<string|null>(null);
  const matches=detail&&findQuery.trim()?detail.blocks.filter(b=>b.text.toLocaleLowerCase().includes(findQuery.trim().toLocaleLowerCase())):[];
  function capture():ReadingPosition|null{
    const container=scroll.current;if(!container||!detail)return null;
    const top=container.getBoundingClientRect().top,blocks=[...container.querySelectorAll<HTMLElement>('[data-block-id]')];
    const block=blocks.find(x=>x.getBoundingClientRect().bottom>top+2),rect=block?.getBoundingClientRect();
    return {scroll:container.scrollTop,anchor:block&&rect&&rect.top<=top+5?block.dataset.blockId||null:null,offset:rect?Math.max(0,Math.min(1,(top-rect.top)/Math.max(rect.height,1))):0};
  }
  function go(blockId:string){const container=scroll.current,block=container?.querySelector<HTMLElement>(`[data-block-id="${blockId}"]`);if(container&&block){container.scrollTop+=block.getBoundingClientRect().top-container.getBoundingClientRect().top-12;setFocusedBlock(blockId);}}
  useImperativeHandle(ref,()=>({capture,find:()=>{setFindOpen(true);requestAnimationFrame(()=>findInput.current?.focus());}}));
  useEffect(()=>{setReferenceOpen(false);setFindQuery('');setMatchIndex(0);setFocusedBlock(null);},[lesson.id]);
  useLayoutEffect(()=>{
    const container=scroll.current;if(!container||!detail)return;
    restoring.current=true;
    if(jump&&jump.id===detail.id&&jump.serial!==lastJump.current){lastJump.current=jump.serial;if(jump.blockId)go(jump.blockId);else container.scrollTop=0;if(jump.source==='body'){setFindQuery(jump.query);setFindOpen(true);}if(jump.source==='notes')props.onNoteOpen(true);}
    else{const position=props.position();const block=position?.anchor?container.querySelector<HTMLElement>(`[data-block-id="${position.anchor}"]`):null;
      if(block&&position)container.scrollTop+=block.getBoundingClientRect().top-container.getBoundingClientRect().top+block.getBoundingClientRect().height*position.offset;
      else container.scrollTop=position?.scroll||0;}
    const frame=requestAnimationFrame(()=>{restoring.current=false;});return()=>cancelAnimationFrame(frame);
  },[detail?.id,preferences.fontSize,preferences.lineHeight,preferences.readingWidth,noteOpen,props.collapsed,jump?.serial]);
  function findNext(direction:number){if(!matches.length)return;const index=(matchIndex+direction+matches.length)%matches.length;setMatchIndex(index);go(matches[index].id);}
  function updateFind(query:string){setFindQuery(query);setMatchIndex(0);const first=detail?.blocks.find(b=>query.trim()&&b.text.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));if(first)go(first.id);}
  const previous=props.directory.filter(x=>x.order<lesson.order).at(-1),next=props.directory.find(x=>x.order>lesson.order);
  return <main className={`reader-page ${noteOpen?'has-notes':''}`}><aside className="reader-directory"><div className="directory-heading"><BookOpen size={17}/><strong>{lesson.seasonName}</strong><span>{props.directory.length}篇</span></div><div className="directory-list">{props.directory.map(l=><button title={l.title} className={l.id===lesson.id?'selected':''} key={l.id} onClick={()=>props.onOpen(l.id)}><span>{String(l.order).padStart(3,'0')}</span><div>{l.title}<small>{l.audio?'音频 · 文稿':'当前无音频'}</small></div></button>)}</div></aside><div className="reading-area"><div className="reading-toolbar"><button className="text-button" onClick={props.onBack}><ArrowLeft size={15}/> {props.backLabel||'返回书架'}</button><div>{lesson.audio&&<button className="reader-play-button" aria-label={props.isPlaying?'暂停本课':'播放本课'} onClick={props.onPlay}>{props.isPlaying?<Pause size={15}/>:<Play size={15}/>}<span>{props.isPlaying?'暂停本课':'播放本课'}</span></button>}<button className={`icon-button ${props.flag?.favorite?'is-on':''}`} aria-label={props.flag?.favorite?'取消收藏':'收藏课程'} onClick={()=>props.onFlag('favorite',!props.flag?.favorite)}><Star size={16} fill={props.flag?.favorite?'currentColor':'none'}/></button><button className={`icon-button ${props.flag?.finished?'is-on':''}`} aria-label={props.flag?.finished?'取消已学完':'标记已学完'} onClick={()=>props.onFlag('finished',!props.flag?.finished)}><CheckCircle2 size={17}/></button><button className="icon-button" aria-label="加入播放队列" disabled={!lesson.audio} onClick={props.onAddQueue}><Headphones size={17}/></button><button className="icon-button" aria-label="文内查找" title="Ctrl+F 文内查找" onClick={()=>{setFindOpen(!findOpen);requestAnimationFrame(()=>findInput.current?.focus());}}><Search size={16}/></button><button className="icon-button" aria-label="专注阅读" onClick={props.onFocus}><Maximize2 size={16}/></button><button className={`icon-button ${noteOpen?'is-on':''}`} aria-label={noteOpen?'收起课程笔记':'打开课程笔记'} onClick={()=>props.onNoteOpen(!noteOpen)}><NotebookPen size={18}/></button></div></div>
    <div className="reading-preferences"><label>字号<select aria-label="正文字号" value={preferences.fontSize} onChange={e=>props.onPreferences({fontSize:Number(e.target.value)})}>{[16,18,20,22,24].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>行距<select aria-label="正文行距" value={preferences.lineHeight} onChange={e=>props.onPreferences({lineHeight:Number(e.target.value)})}>{[1.6,1.8,2,2.2].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>宽度<select aria-label="阅读宽度" value={preferences.readingWidth} onChange={e=>props.onPreferences({readingWidth:e.target.value as Preferences['readingWidth']})}><option value="narrow">窄</option><option value="comfortable">适中</option><option value="wide">宽</option></select></label></div>
    <AnnotationTools detail={detail} currentBlock={()=>capture()?.anchor||detail?.blocks[0]?.id||null} audioPosition={props.audioPosition} onSource={props.onSource}/>
    {findOpen&&<div className="document-find"><Search size={15}/><input ref={findInput} aria-label="查找文内文字" placeholder="查找这篇文稿" value={findQuery} maxLength={100} onChange={e=>updateFind(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();findNext(e.shiftKey?-1:1);}if(e.key==='Escape')setFindOpen(false);}}/><span>{matches.length?`${matchIndex+1}/${matches.length} 个段落`:'无匹配段落'}</span><button aria-label="上一个匹配段落" disabled={!matches.length} onClick={()=>findNext(-1)}><ChevronLeft size={17}/></button><button aria-label="下一个匹配段落" disabled={!matches.length} onClick={()=>findNext(1)}><ChevronRight size={17}/></button><button aria-label="关闭文内查找" onClick={()=>{setFindOpen(false);setFindQuery('');setFocusedBlock(null);}}><X size={16}/></button></div>}
    <div className="reading-scroll" ref={scroll} onScroll={()=>{if(restoring.current)return;const position=capture();if(position)props.onRead(lesson.id,position);}}>{props.error?<div role="alert" className="empty-state">{props.error}<button className="text-button" onClick={()=>props.onOpen(lesson.id)}>重新打开课程</button></div>:detail?<article className="article" style={{maxWidth:preferences.readingWidth==='narrow'?540:preferences.readingWidth==='wide'?980:740}}><div className="article-eyebrow">{detail.seasonName} / {detail.topic||'日课书桌'}</div><h1>{detail.title}</h1><div className="article-meta">{detail.author&&<span>{detail.author}</span>}<span>{detail.date||'未设置日期'}{detail.date&&!detail.dateVerified?'（日期待核实）':''}</span><span>{detail.audio?`${Math.round(detail.audio.duration/60)} 分钟`:'文稿阅读'}</span><Status lesson={detail}/></div>{detail.textStatus!=='available'&&<div className="content-notice"><FileText size={19}/><div><strong>{detail.textStatus==='missing_body'?'当前资料暂缺对应正文':'现有正文不完整'}</strong><p>{detail.statusNote||(detail.textStatus==='missing_body'?'本讲仍可收听音频、记录笔记。现有资料没有取得对应正文。':'源页面仅保留部分正文，下方展示现有片段，可收听本讲音频。')}</p></div></div>}{!detail.audio&&<div className="text-only-notice"><FileText size={16}/>当前资料没有对应音频，可以阅读和记笔记。</div>}<div className="markdown" style={{fontSize:preferences.fontSize,lineHeight:preferences.lineHeight}}>{detail.blocks.map(block=><section data-block-id={block.id} key={block.id} className={`paragraph-block ${focusedBlock===block.id?'focused-block':''} ${findQuery.trim()&&block.text.toLocaleLowerCase().includes(findQuery.trim().toLocaleLowerCase())?'matching-block':''}`}><ReactMarkdown skipHtml remarkPlugins={[remarkGfm]} components={{a:({children})=><span className="source-link">{children}</span>,img:()=>null}}>{block.text}</ReactMarkdown></section>)}</div>{detail.attachments.length>0&&<div className="reference-section"><button onClick={()=>setReferenceOpen(!referenceOpen)}><FileText size={18}/><div><strong>课程插图</strong><span>查看文稿中的本地图片</span></div><ChevronDown size={17}/></button>{referenceOpen&&<div className="reference-images">{detail.attachments.map((a,i)=><img key={a.url} src={a.url} alt={`课程插图第${i+1}段`} loading="lazy"/>)}</div>}</div>}<div className="article-end"><span/>正文结束<span/></div><div className="article-next"><button disabled={!previous} onClick={()=>previous&&props.onOpen(previous.id)}><ChevronLeft size={17}/>上一篇</button><button disabled={!next} onClick={()=>next&&props.onOpen(next.id)}>下一篇<ChevronRight size={17}/></button></div></article>:<div className="empty-state">正在打开文稿…</div>}</div></div>{noteOpen&&<aside className="reader-notes"><div className="notes-heading"><NotebookPen size={18}/><strong>课程笔记</strong><button aria-label="关闭课程笔记" onClick={()=>props.onNoteOpen(false)}><X size={17}/></button></div><div className="notes-course">{lesson.title}</div><NoteEditor key={lesson.id} id={lesson.id} onSaved={props.onSaved} highlight={jump?.id===lesson.id&&jump.source==='notes'?jump.query:''}/></aside>}</main>;
});
export default Reader;
