import {useEffect,useState} from 'react';
import {ArrowRight,CheckCircle2,Plus,RefreshCw} from 'lucide-react';
import type {Card,CardDraft,Lesson,Source} from './types';
import CardDialog,{today} from './CardDialog';
const draft=(c:Card):CardDraft=>({id:c.id,question:c.question,answer:c.answer,dueDay:c.due_day,paused:!!c.paused,lessonId:c.lesson_id||undefined,blockId:c.block_id,audioPosition:c.audio_position,noteId:c.note_id||undefined,annotationId:c.annotation_id||undefined,sourceQuote:c.source_quote});
export default function ReviewPage({lessons,onSource}:{lessons:Lesson[];onSource:(source:Source)=>void}){
  const [cards,setCards]=useState<Card[]>([]),[editing,setEditing]=useState<CardDraft|null>(null),[tab,setTab]=useState('due'),[selected,setSelected]=useState<string|null>(null),[revealed,setRevealed]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function refresh(){try{setCards(await window.learning.cards());}catch{setMessage('复习记录暂时无法读取。');}}
  useEffect(()=>{void refresh();},[]);const date=today(),due=cards.filter(c=>!c.paused&&c.due_day<=date),filtered=tab==='due'?due:tab==='paused'?cards.filter(c=>c.paused):cards;
  const current=filtered.find(c=>c.id===selected)||filtered[0];useEffect(()=>{setRevealed(false);},[current?.id,tab]);
  async function feedback(rating:string){if(!current||!revealed||busy)return;setBusy(true);try{const card=await window.learning.rateCard(current.id,rating);setCards(old=>old.map(c=>c.id===card.id?card:c));setSelected(null);setRevealed(false);setMessage(`已记录反馈，下次复习：${card.due_day}。`);}catch{setMessage('复习反馈尚未保存，请重试。');}finally{setBusy(false);}}
  return <main className="review-page page-scroll"><header className="workspace-heading"><div><div className="eyebrow">REVISIT AN IDEA</div><h1>间隔复习</h1><p>先试着回忆，再看答案；按自己的掌握程度安排下一次。</p></div><button className="primary-button" onClick={()=>setEditing({question:'',answer:''})}><Plus size={17}/>新建复习卡</button></header>{message&&<div role="status" className="inline-message">{message}<button onClick={()=>setMessage('')}>关闭</button></div>}<div className="review-tabs">{[['due',`今天到期 ${due.length}`],['all',`全部卡片 ${cards.length}`],['paused','已暂停']].map(([id,name])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setSelected(null);}}>{name}</button>)}</div><div className="review-columns"><aside className="review-card-list">{filtered.map(c=><button key={c.id} data-card-id={c.id} className={c.id===current?.id?'active':''} onClick={()=>setSelected(c.id)}><strong>{c.question}</strong><small>{c.paused?'已暂停':'下次 '+c.due_day} · 复习 {c.repetitions} 次</small></button>)}</aside>{current?<section className="practice-card"><div className="practice-meta"><span><RefreshCw size={16}/> {current.paused?'已暂停':current.due_day<=date?'到期复习':'尚未到期'}</span><button className="text-button" onClick={()=>setEditing(draft(current))}>编辑卡片与日期</button></div><h2>{current.question}</h2>{!revealed?<button className="primary-button" onClick={()=>setRevealed(true)}>显示答案</button>:<><div className="review-answer" data-testid="review-answer">{current.answer||'这张卡片尚未填写答案，可以编辑补充。'}</div>{current.source_quote&&<blockquote>{current.source_quote}</blockquote>}<div className="feedback-buttons">{[['again','没记住'],['hard','有点难'],['good','记住了'],['easy','很熟悉']].map(([id,name])=><button key={id} disabled={busy||!!current.paused||current.due_day>date} onClick={()=>void feedback(id)}>{name}</button>)}</div><p className="review-help">依据自评安排下次日期，不把打开答案视为掌握。</p></>}{current.lesson_id&&<button className="note-source" onClick={()=>onSource({lessonId:current.lesson_id!,blockId:current.block_id,audioPosition:current.audio_position})}>回到出处 · {lessons.find(l=>l.id===current.lesson_id)?.title} <ArrowRight size={14}/></button>}<footer><span>间隔 {current.interval_days} 天 · 遗忘反馈 {current.lapses} 次</span><button className="text-button" onClick={async()=>{await window.learning.saveCard({...draft(current),paused:!current.paused});await refresh();}}> {current.paused?'恢复复习':'暂停复习'}</button></footer></section>:<section className="practice-card review-empty"><CheckCircle2 size={46}/><h2>{tab==='due'?'今天的到期复习已完成。':'这里还没有卡片。'}</h2><p>可以从笔记或文中摘录创建复习卡，<br/>也可以自己写一个值得回忆的问题。</p></section>}</div>{editing&&<CardDialog draft={editing} onClose={()=>setEditing(null)} onSaved={()=>{void refresh();setMessage('复习卡已保存。');}}/>}</main>;
}
