import {useEffect,useRef,useState} from 'react';
import {ChevronLeft,ChevronRight,Search} from 'lucide-react';
import type {Lesson,SearchOptions,SearchResult,SearchResults} from './types';
import {useSessionState,useScrollMemory,useFilterReset} from './session';
import {courseGroups} from './common';
export default function SearchPage({onOpen,lessons}:{onOpen:(result:SearchResult,query:string)=>void;lessons:Lesson[]}){
  const [query,setQuery]=useSessionState('search.query',''),[scope,setScope]=useSessionState<SearchOptions['scope']>('search.scope','all'),[season,setSeason]=useSessionState('search.season',0),[page,setPage]=useSessionState('search.page',0),[results,setResults]=useState<SearchResults|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const request=useRef(0),input=useRef<HTMLInputElement>(null);
  useEffect(()=>{input.current?.focus();},[]);
  const scroll=useScrollMemory<HTMLElement>('search.scroll',!!results);
  useFilterReset([query,scope,season],()=>{setPage(0);if(scroll.current)scroll.current.scrollTop=0;});
  useEffect(()=>{const token=++request.current;setError('');if(!query.trim()){setResults(null);setBusy(false);return;}setBusy(true);const timer=setTimeout(()=>{window.learning.search({query:query.trim(),scope,season,page}).then(value=>{if(token===request.current){setResults(value);setBusy(false);}}).catch(()=>{if(token===request.current){setError('搜索暂时无法完成，请重试。');setBusy(false);}});},180);return()=>clearTimeout(timer);},[query,scope,season,page]);
  const sources={title:'标题命中',body:'正文命中',notes:'笔记命中'};
  return <main ref={scroll} className="search-page page-scroll"><div className="page-heading"><div><div className="eyebrow">FIND AN IDEA</div><h1>全文搜索</h1><p>搜索课程标题、正文与笔记。</p></div></div><label className="full-search-box"><Search size={21}/><input ref={input} aria-label="搜索标题正文和笔记" placeholder="试试：决策、运气、心流" maxLength={100} value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="search-filters"><div className="season-tabs">{(['all','title','body','notes'] as const).map((value,i)=><button className={scope===value?'selected':''} key={value} onClick={()=>setScope(value)}>{['全部','标题','正文','笔记'][i]}</button>)}</div><select aria-label="搜索分组" value={season} onChange={e=>setSeason(Number(e.target.value))}><option value={0}>全部课程</option>{courseGroups(lessons).map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select></div>{error&&<div role="alert" className="content-notice">{error}</div>}{!query.trim()?<div className="empty-state"><Search size={35}/><h2>输入关键词开始搜索</h2><p>支持中文短词；点击正文结果可定位到命中的段落。</p></div>:<><div className="results-label">{busy?'正在搜索…':`${results?.total||0} 条课程 / 笔记匹配`}<span>每页 20 条 · 标题优先</span></div><div className="search-results" aria-busy={busy}>{results?.results.map(result=><button data-search-id={result.id} key={result.id} onClick={()=>onOpen(result,results.query)}><div><span className="source-chip">{sources[result.source]}</span><span>{result.season?courseGroups(lessons).find(g=>g.id===result.season)?.name||'课程':'独立笔记'}</span></div><h2>{result.title}</h2><p>{result.snippet}</p><span className="text-button">{result.source==='body'?'定位正文段落':result.source==='notes'?(result.noteId?'打开个人笔记':'打开课程笔记'):'打开课程'} <ChevronRight size={15}/></span></button>)}</div>{!busy&&!results?.total&&<div className="empty-state"><h2>没有找到这个关键词</h2><p>试试缩短关键词，或选择全部内容和全部课程。</p></div>}<div className="pagination"><span>第 {page+1} / {Math.max(1,Math.ceil((results?.total||0)/20))} 页</span><button aria-label="上一页搜索结果" disabled={!page||busy} onClick={()=>setPage(page-1)}><ChevronLeft size={17}/></button><button aria-label="下一页搜索结果" disabled={busy||(page+1)*20>=(results?.total||0)} onClick={()=>setPage(page+1)}><ChevronRight size={17}/></button></div></>}</main>;
}
