export type Lesson={id:string;author:string;season:number;seasonName:string;order:number;title:string;date:string;dateVerified:boolean;topic:string;kind:string;textStatus:'available'|'missing_body'|'partial_body';audio:null|{duration:number;format:string;url:string};attachmentCount:number;duplicateOf:string|null};
export type Block={id:string;order:number;text:string};
export type Detail=Lesson&{markdown:string;blocks:Block[];statusNote:string;attachments:{url:string;width:number;height:number}[]};
export type Note={id:string;lesson_id:string|null;content:string;created_at:string;updated_at:string;title:string;kind:'course'|'free'|'excerpt';tags:string[];source_lesson:string|null;source_block:string|null;source_quote:string;deleted_at:string|null};
export type Progress={lesson_id:string;audio_position:number;read_scroll:number;updated_at:string;read_anchor:string|null;anchor_offset:number};
export type Flag={lesson_id:string;favorite:number;finished:number;started:number};
export type Bootstrap={lessons:Lesson[];settings:Record<string,unknown>;recent:Progress[];flags:Flag[];version:string;contentVersion:string};
export type SearchResult={id:string;title:string;season:number;source:'title'|'body'|'notes';blockId:string|null;snippet:string;noteId?:string};
export type SearchResults={query:string;total:number;page:number;pageSize:number;results:SearchResult[]};
export type SearchOptions={query:string;scope:'all'|'title'|'body'|'notes';season:number;page:number};
export type SleepState={mode:'off'|'deadline'|'end';deadline:number|null};
export type RuntimeEvent={type:'sleep-expired'|'timer-changed'|'suspend'|'resume'|'data-restored'|'backup-error';timer?:SleepState;message?:string};
export type Preferences={fontSize:number;lineHeight:number;readingWidth:'narrow'|'comfortable'|'wide'};
export type SelectionBlock={lessonId:string;blockId:string;quote:string;start:number;end:number;prefix:string;suffix:string;color:'yellow'|'green'|'blue';comment:string};
export type Annotation={id:string;lesson_id:string;block_id:string;quote:string;start_offset:number;end_offset:number;prefix:string;suffix:string;comment:string;color:'yellow'|'green'|'blue';resolved_block_id:string|null;anchor_state:'anchored'|'reanchored'|'orphaned';anchor_reason?:string};
export type Bookmark={id:string;lesson_id:string;kind:'paragraph'|'audio';block_id:string|null;audio_position:number|null;label:string;created_at:string};
export type Source={lessonId?:string;blockId?:string|null;audioPosition?:number|null;noteId?:string;annotationId?:string;sourceQuote?:string};
export type Card={id:string;question:string;answer:string;lesson_id:string|null;block_id:string|null;audio_position:number|null;note_id:string|null;annotation_id:string|null;source_quote:string;due_day:string;interval_days:number;repetitions:number;lapses:number;paused:number;last_rating:string|null};
export type CardDraft=Source&{id?:string;question:string;answer:string;dueDay?:string;paused?:boolean};
export type Plan={id:string;name:string;lesson_ids:string[];daily_limit:number;start_day:string;end_day:string|null;paused:number};
export type StudySample={sessionId:string;sequence:number;lessonId:string;day:string;startedAt:string;audioSeconds:number;readSeconds:number;totalSeconds:number;intervals:number[][]};
export type StudyData={today:string;goalMinutes:number;flags:Flag[];days:{day:string;audio_seconds:number;read_seconds:number;total_seconds:number}[];courses:{day:string;lesson_id:string;audio_seconds:number;read_seconds:number;total_seconds:number}[];coverage:{lesson_id:string;intervals:number[][]}[];reviews:{card_id:string;rating:string;day:string;due_after:string}[];plans:Plan[];cards:Card[]};
export type Asset={id:string;note_id:string;name:string;file_name:string;bytes:number;sha256:string;url:string};
export type BackupStatus={enabled:boolean;folder:string;files:{name:string;bytes:number}[]};
declare global {interface Window {learning:{
  audioMetadata(id:string,duration:number):Promise<number>;bootstrap():Promise<Bootstrap>;lesson(id:string):Promise<Detail>;note(id:string):Promise<Note|null>;notes():Promise<Note[]>;
  saveNote(id:string,content:string):Promise<Note|null>;setSetting(key:string,value:unknown):Promise<void>;
  progress(id:string):Promise<Progress|null>;saveProgress(id:string,position:number,scroll:number,anchor?:string|null,offset?:number):Promise<void>;
  search(options:SearchOptions):Promise<SearchResults>;flags():Promise<Flag[]>;setFlag(id:string,key:'favorite'|'finished'|'started',value:boolean):Promise<Flag>;
  sleepTimer():Promise<SleepState>;setSleepTimer(options:{mode:'off'|'minutes'|'end';minutes?:number}):Promise<SleepState>;lessonEnded():Promise<boolean>;
  allNotes(deleted?:boolean):Promise<Note[]>;editNote(item:Partial<Note>&{kind:Note['kind'];sourceLesson?:string;sourceBlock?:string|null;sourceQuote?:string}):Promise<Note>;trashNote(id:string,restore?:boolean):Promise<Note>;
  annotations(id:string,deleted?:boolean):Promise<Annotation[]>;addAnnotations(items:SelectionBlock[]):Promise<Annotation[]>;editAnnotation(id:string,comment:string,color:string):Promise<void>;trashAnnotation(id:string,restore?:boolean):Promise<void>;reanchorAnnotation(id:string,item:SelectionBlock):Promise<void>;
  bookmarks(id?:string):Promise<Bookmark[]>;addBookmark(item:{lessonId:string;kind:Bookmark['kind'];blockId?:string|null;position?:number|null;label?:string}):Promise<Bookmark>;removeBookmark(id:string):Promise<void>;
  cards():Promise<Card[]>;saveCard(item:CardDraft):Promise<Card>;rateCard(id:string,rating:string):Promise<Card>;
  savePlan(item:{id?:string;name:string;lessonIds:string[];dailyLimit:number;startDay:string;endDay?:string|null;paused?:boolean}):Promise<string>;removePlan(id:string):Promise<void>;removedPlans():Promise<Plan[]>;restorePlan(id:string):Promise<string>;studyData():Promise<StudyData>;recordLearning(item:StudySample):Promise<boolean>;
  assets(noteId?:string):Promise<Asset[]>;importAsset(target:{lessonId?:string;noteId?:string}):Promise<Asset|null>;removeAsset(id:string):Promise<void>;
  exportNotes(options:{format:'markdown'|'pdf';noteIds?:string[]}):Promise<{file:string;bytes:number;entries:number}|null>;backupNow():Promise<{file:string;bytes:number}|null>;restoreBackup():Promise<{beforeRestore:string;notes:number;cards:number}|null>;backupStatus():Promise<BackupStatus>;automaticBackup():Promise<{file:string}|null>;openBackupFolder():Promise<void>;
  onRuntimeEvent(callback:(event:RuntimeEvent)=>void):()=>void;
  diagnostics():Promise<Record<string,unknown>>;
  onPrepareRestore(callback:()=>Promise<void>):()=>void;
  onPrepareClose(callback:()=>Promise<void>):()=>void;
}}}
