import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowRight,BookOpen,FileText,Headphones,Home,Library,Moon,NotebookPen,PanelLeftClose,PanelLeftOpen,Search,Settings,Sun,X,CalendarDays,RefreshCw} from 'lucide-react';
import type {Bootstrap,Detail,Flag,Note,Preferences,SearchResult,Source} from './types';
import {flushNotes,courseGroups,appConfig} from './common';
import Player from './Player';
import type {PlayerHandle} from './Player';
import Reader from './Reader';
import type {Jump,ReaderHandle,ReadingPosition} from './Reader';
import SearchPage from './SearchPage';
import LibraryPage from './LibraryPage';
import NoteWorkspace from './NoteWorkspace';
import ReviewPage from './ReviewPage';
import StudyPage,{StudySummary} from './StudyPage';
import BackupPanel from './BackupPanel';
import LearningTracker from './LearningTracker';
type Page='home'|'library'|'reader'|'notes'|'settings'|'search'|'study'|'review';
type Position=ReadingPosition&{audio:number};
const fresh=():Position=>({audio:0,scroll:0,anchor:null,offset:0});
export default function App(){
  const [data,setData]=useState<Bootstrap|null>(null),[page,setPage]=useState<Page>('home'),[selected,setSelected]=useState(''),[audioId,setAudioId]=useState(''),[isPlaying,setIsPlaying]=useState(false),[detail,setDetail]=useState<Detail|null>(null),[readerError,setReaderError]=useState(''),[error,setError]=useState(''),[toast,setToast]=useState(''),[theme,setTheme]=useState('light'),[collapsed,setCollapsed]=useState(false),[noteOpen,setNoteOpen]=useState(true),[season,setSeason]=useState(0),[notes,setNotes]=useState<Note[]>([]),[flags,setFlags]=useState<Record<string,Flag>>({}),[rate,setRate]=useState(1),[volume,setVolume]=useState(.8),[continuous,setContinuous]=useState(false),[queue,setQueue]=useState<string[]>([]),[autoplay,setAutoplay]=useState(0),[jump,setJump]=useState<Jump|null>(null),[preferences,setPreferences]=useState<Preferences>({fontSize:18,lineHeight:2,readingWidth:'comfortable'});
  const [readerOrigin,setReaderOrigin]=useState<Page>('library'),[selectedNote,setSelectedNote]=useState<string|null>(null),[seekRequest,setSeekRequest]=useState<{serial:number;id:string;position:number}|null>(null);const seekSerial=useRef(0);
  const reader=useRef<ReaderHandle>(null),player=useRef<PlayerHandle>(null),positions=useRef(new Map<string,Position>()),loadedRead=useRef(new Set<string>()),lastSave=useRef(new Map<string,number>()),startedPending=useRef(new Set<string>()),transition=useRef(0),jumpSerial=useRef(0),selectedRef=useRef(selected),audioIdRef=useRef(audioId),audioTransition=useRef(0),callbacks=useRef({close:async()=>{},suspend:async()=>{}});
  selectedRef.current=selected;audioIdRef.current=audioId;
  const refreshNotes=useCallback(()=>{void window.learning.allNotes().then(setNotes).catch(()=>setError('笔记暂时无法读取'));void window.learning.flags().then(rows=>setFlags(Object.fromEntries(rows.map(x=>[x.lesson_id,x])))).catch(()=>setError('学习状态暂时无法读取'));},[]);
  useEffect(()=>{window.learning.bootstrap().then(d=>{setData(d);setSelected(d.lessons.some(l=>l.id===d.settings.lastLesson)?String(d.settings.lastLesson):d.lessons[0]?.id||'');setAudioId(d.lessons.find(l=>l.id===d.settings.lastAudioLesson&&l.audio)?.id||d.lessons.find(l=>l.id===d.settings.lastLesson&&l.audio)?.id||d.lessons.find(l=>l.audio)?.id||'');setTheme(d.settings.theme==='dark'?'dark':'light');setCollapsed(d.settings.sidebarCollapsed===true);setRate(typeof d.settings.playbackRate==='number'?d.settings.playbackRate:1);setVolume(typeof d.settings.volume==='number'?d.settings.volume:.8);setContinuous(d.settings.continuousPlay===true);setQueue(Array.isArray(d.settings.playQueue)?(d.settings.playQueue as string[]).filter(id=>d.lessons.some(l=>l.id===id&&l.audio)):[]);setPreferences({fontSize:typeof d.settings.fontSize==='number'?d.settings.fontSize:18,lineHeight:typeof d.settings.lineHeight==='number'?d.settings.lineHeight:2,readingWidth:['narrow','comfortable','wide'].includes(String(d.settings.readingWidth))?d.settings.readingWidth as Preferences['readingWidth']:'comfortable'});setFlags(Object.fromEntries(d.flags.map(f=>[f.lesson_id,f])));}).catch(()=>setError('课程库加载失败，请先运行资料导入和索引生成命令。'));refreshNotes();},[]);
  useEffect(()=>{document.title=appConfig.name;},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;},[theme]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(timer);},[toast]);
  useEffect(()=>{if(!data||!selected)return;let alive=true;setDetail(null);setReaderError('');Promise.allSettled([window.learning.lesson(selected),window.learning.progress(selected)]).then(([body,saved])=>{if(!alive)return;if(saved.status==='fulfilled'&&!loadedRead.current.has(selected)){const progress=saved.value;positions.current.set(selected,{audio:positions.current.get(selected)?.audio??progress?.audio_position??0,scroll:progress?.read_scroll||0,anchor:progress?.read_anchor||null,offset:progress?.anchor_offset||0});loadedRead.current.add(selected);}if(body.status==='fulfilled')setDetail(body.value);else setReaderError('正文资源暂时无法读取。音频仍可尝试播放，也可以记录笔记。');if(saved.status==='rejected')setError('阅读位置暂时无法读取');});return()=>{alive=false;};},[selected,!!data]);
  function snapshotReading(){const position=reader.current?.capture();if(position){const id=selectedRef.current;positions.current.set(id,{...(positions.current.get(id)||fresh()),...position});}}
  async function savePosition(id:string){
    if(!positions.current.has(id))return;
    if(!loadedRead.current.has(id)){
      const saved=await window.learning.progress(id),cached=positions.current.get(id)||fresh();
      if(!loadedRead.current.has(id)){positions.current.set(id,{...cached,scroll:saved?.read_scroll||0,anchor:saved?.read_anchor||null,offset:saved?.anchor_offset||0});loadedRead.current.add(id);}
    }
    const position=positions.current.get(id)!;
    await window.learning.saveProgress(id,position.audio,position.scroll,position.anchor,position.offset);lastSave.current.set(id,Date.now());
  }
  async function saveOpenPositions(){await Promise.all([...new Set([selectedRef.current,audioIdRef.current])].map(savePosition));}
  async function selectAudio(id:string,auto=true){
    if(!data?.lessons.find(l=>l.id===id)?.audio)return;
    const token=++audioTransition.current;
    if(id!==audioIdRef.current){
      player.current?.pause();await savePosition(audioIdRef.current);if(token!==audioTransition.current)return;
      setAudioId(id);audioIdRef.current=id;await saveSetting('lastAudioLesson',id);
    }
    if(token!==audioTransition.current)return;
    if(auto)setAutoplay(value=>value+1);
  }
  function captureAudio(id:string,value:number,commit:boolean){positions.current.set(id,{...(positions.current.get(id)||fresh()),audio:value});if(commit&&!flags[id]?.started&&!startedPending.current.has(id)){startedPending.current.add(id);void setFlag(id,'started',true).finally(()=>startedPending.current.delete(id));}if(commit&&Date.now()-(lastSave.current.get(id)||0)>4000)void savePosition(id).catch(()=>setError('播放位置保存失败'));}
  function captureRead(id:string,position:ReadingPosition){positions.current.set(id,{...(positions.current.get(id)||fresh()),...position});if(Date.now()-(lastSave.current.get(id)||0)>3000)void savePosition(id).catch(()=>setError('阅读位置保存失败'));}
  async function saveSetting(key:string,value:unknown){try{await window.learning.setSetting(key,value);}catch{setError('偏好保存失败，请重试');}}
  async function setFlag(id:string,key:'favorite'|'finished'|'started',value:boolean){try{const row=await window.learning.setFlag(id,key,value);setFlags(old=>({...old,[id]:row}));}catch{setError('课程状态保存失败');}}
  async function changePage(value:Page){const token=++transition.current;snapshotReading();try{await flushNotes();await savePosition(selectedRef.current);if(token===transition.current)setPage(value);}catch{setError('数据尚未保存，请重试切换页面');}}
  async function openLesson(id:string,auto=false,target?:Omit<Jump,'serial'|'id'>,keepPage=false){
    const token=++transition.current;snapshotReading();
    try{await flushNotes();await savePosition(selectedRef.current);if(token!==transition.current)return;
      if(id===selectedRef.current&&readerError){setReaderError('');setDetail(await window.learning.lesson(id));}
      setSelected(id);if(!keepPage){if(page!=='reader')setReaderOrigin(page);setPage('reader');}
      if(target){setJump({...target,id,serial:++jumpSerial.current});if(target.source==='notes')setNoteOpen(true);}else setJump(null);
      await saveSetting('lastLesson',id);setData(old=>old?{...old,settings:{...old.settings,lastLesson:id}}:old);await setFlag(id,'started',true);
      if(auto)await selectAudio(id,true);else if(!player.current?.isPlaying()&&data?.lessons.find(l=>l.id===id)?.audio)await selectAudio(id,false);
    }catch{setError('课程切换前的数据未能保存，请重试');}
  }
  callbacks.current.close=async()=>{snapshotReading();player.current?.pause();await flushNotes();await saveOpenPositions();};
  callbacks.current.suspend=async()=>{snapshotReading();player.current?.pause();await flushNotes();await saveOpenPositions();};
  useEffect(()=>window.learning.onPrepareClose(()=>callbacks.current.close()),[]);
  useEffect(()=>window.learning.onPrepareRestore(()=>callbacks.current.close()),[]);
  useEffect(()=>window.learning.onRuntimeEvent(event=>{if(event.type==='data-restored')setTimeout(()=>window.location.reload(),100);if(event.type==='backup-error')setError('自动备份未完成，请在阅读偏好中重试。');if(event.type==='suspend')void callbacks.current.suspend().catch(()=>setError('休眠前的数据保存失败'));if(event.type==='resume'){player.current?.pause();setToast('已从休眠恢复，点击播放继续。');}if(event.type==='sleep-expired'){player.current?.pause();setToast('定时已到，音频已停止。');}}),[]);
  useEffect(()=>{const keyboard=(event:KeyboardEvent)=>{if(document.querySelector('[aria-modal="true"]')||!(event.ctrlKey||event.metaKey))return;if(event.key.toLowerCase()==='k'){event.preventDefault();void changePage('search');}else if(event.key.toLowerCase()==='f'&&page==='reader'){event.preventDefault();reader.current?.find();}};window.addEventListener('keydown',keyboard);return()=>window.removeEventListener('keydown',keyboard);},[page]);
  function changeTheme(){const value=theme==='light'?'dark':'light';setTheme(value);void saveSetting('theme',value);}
  function changeCollapsed(value:boolean){snapshotReading();setCollapsed(value);void saveSetting('sidebarCollapsed',value);}
  function changeNoteOpen(value:boolean){snapshotReading();setNoteOpen(value);}
  function updatePreferences(values:Partial<Preferences>){snapshotReading();setPreferences(old=>({...old,...values}));for(const [key,value] of Object.entries(values))void saveSetting(key,value);}
  function updateQueue(ids:string[]){const valid=new Set(data?.lessons.filter(l=>l.audio).map(l=>l.id));const items=[...new Set(ids)].filter(id=>valid.has(id));setQueue(items);void saveSetting('playQueue',items);setToast(items.length?`播放队列已有 ${items.length} 篇课程。`:'播放队列已清空。');}
  function addQueue(ids:string[]){updateQueue([...queue,...ids]);}
  async function openSource(source:Source){if(!source.lessonId)return;await openLesson(source.lessonId,false,source.blockId?{blockId:source.blockId,query:'',source:'body'}:undefined);if(source.audioPosition!==null&&source.audioPosition!==undefined){await selectAudio(source.lessonId,false);setSeekRequest({id:source.lessonId,position:source.audioPosition,serial:++seekSerial.current});}}
  function openSearchResult(result:SearchResult,query:string){if(result.noteId){void changePage('notes').then(()=>setSelectedNote(result.noteId!));}else void openLesson(result.id,false,{blockId:result.blockId,query,source:result.source});}
  if(!data)return <div className="loading"><BookOpen size={35}/><h1>{appConfig.name}</h1><p>{error||'正在打开课程书架…'}</p></div>;
  const lessons=data.lessons,current=lessons.find(l=>l.id===selected)||lessons[0],audioLesson=lessons.find(l=>l.id===audioId)||null,directory=lessons.filter(l=>l.season===current.season);
  const titles={home:'学习首页',library:'课程书架',reader:'听读学习',notes:'我的笔记',settings:'阅读偏好',search:'全文搜索',study:'学习计划',review:'间隔复习'};
  return <div className={`app-shell ${collapsed?'sidebar-collapsed':''}`}><aside className="app-sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();void changePage('home');}}><img src="jyrk://app/brand.png" alt={appConfig.name}/><div><strong>{appConfig.name}</strong><span>{appConfig.subtitle}</span></div></a><div className="nav-label">课程与笔记</div><nav>{([{id:'home',text:'学习首页',icon:Home},{id:'library',text:'课程书架',icon:Library},{id:'reader',text:'听读学习',icon:BookOpen},{id:'notes',text:'我的笔记',icon:NotebookPen},{id:'search',text:'全文搜索',icon:Search},{id:'study',text:'学习计划',icon:CalendarDays},{id:'review',text:'间隔复习',icon:RefreshCw}] as const).map(n=><button key={n.id} aria-label={n.text} title={n.text} className={page===n.id?'active':''} onClick={()=>void changePage(n.id)}><n.icon size={19}/><span>{n.text}</span>{n.id==='library'&&<small>{courseGroups(lessons).length}</small>}</button>)}</nav><div className="sidebar-bottom"><button className={page==='settings'?'active':''} onClick={()=>void changePage('settings')} aria-label="阅读偏好"><Settings size={18}/><span>阅读偏好</span></button><button onClick={()=>changeCollapsed(!collapsed)} aria-label={collapsed?'展开主侧栏':'收起主侧栏'}>{collapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}<span>收起侧栏</span></button><span className="app-version">{appConfig.name} v{data.version}</span></div></aside><div className="workspace"><header className="topbar"><div><span className="topbar-title">{titles[page]}</span></div><div className="top-actions"><button className="search-entry" title="Ctrl+K 全文搜索" onClick={()=>void changePage('search')}><Search size={16}/><span>搜索课程与笔记</span><kbd>Ctrl K</kbd></button><button className="icon-button" onClick={changeTheme} aria-label={theme==='light'?'切换深色主题':'切换浅色主题'}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button></div></header>{error&&<div role="alert" className="global-error">{error}<button aria-label="关闭提示" onClick={()=>setError('')}><X size={15}/></button></div>}
    {page==='home'&&<main className="dashboard page-scroll"><section className="welcome"><div className="welcome-copy"><div className="eyebrow"><span/>{appConfig.subtitle}</div><h1>{appConfig.name}</h1><p>阅读文稿，收听课程，整理笔记。</p><button className="primary-button" onClick={()=>void openLesson(selected)}><BookOpen size={16}/>{data.settings.lastLesson?'继续阅读':'开始阅读'}<ArrowRight size={16}/></button></div><div className="welcome-image"><img src="jyrk://app/brand.png" alt={appConfig.name}/></div></section><StudySummary onStudy={()=>void changePage('study')} onReview={()=>void changePage('review')}/><div className="overview"><div><Library size={20}/><strong>{courseGroups(lessons).length}</strong><span>个课程分组</span></div><div><FileText size={20}/><strong>{lessons.length}</strong><span>篇课程条目</span></div><div><Headphones size={20}/><strong>{lessons.filter(l=>l.audio).length}</strong><span>段音频课程</span></div><div><NotebookPen size={20}/><strong>{notes.length}</strong><span>条笔记</span></div></div><section className="season-section"><div className="section-title"><div><h2>课程书架</h2><p>按分组浏览全部课程。</p></div><button className="text-button" onClick={()=>{setSeason(0);void changePage('library');}}>查看全部课程 <ArrowRight size={16}/></button></div><div className="season-grid">{courseGroups(lessons).map((g,i)=>{const group=lessons.filter(l=>l.season===g.id);return <button key={g.id} className={`season-card season-${i%6+1}`} onClick={()=>{setSeason(g.id);void changePage('library');}}><div className="book-spine"/><div className="cover-number">{String(i+1).padStart(2,'0')}</div><div className="cover-label">{appConfig.name}</div><div className="cover-title">{g.name}</div><div className="season-meta">{group.length} 篇课程 · {group.filter(l=>l.audio).length} 篇可听</div><ArrowRight size={18} className="cover-arrow"/></button>;})}</div></section><div className="home-bottom"><span>课程 · 音频、文稿与笔记</span><button className="text-button" onClick={()=>void changePage('search')}>搜索标题、正文与笔记 <Search size={16}/></button></div></main>}
    {page==='library'&&<LibraryPage onPlay={id=>void selectAudio(id,true).catch(()=>setError('音频切换失败，请重试'))} playingId={isPlaying?audioId:null} lessons={lessons} flags={flags} season={season} onSeason={setSeason} onOpen={id=>void openLesson(id)} onFavorite={(id,value)=>void setFlag(id,'favorite',value)} onQueue={addQueue}/>}
    {page==='search'&&<SearchPage lessons={lessons} onOpen={openSearchResult}/>}
    {page==='reader'&&<Reader ref={reader} onPlay={()=>{if(audioId===current.id&&isPlaying)player.current?.pause();else void selectAudio(current.id,true).catch(()=>setError('音频暂时无法打开'));}} isPlaying={audioId===current.id&&isPlaying} lesson={current} detail={detail?.id===current.id?detail:null} error={readerError} directory={directory} noteOpen={noteOpen} onNoteOpen={changeNoteOpen} collapsed={collapsed} onFocus={()=>{changeCollapsed(true);changeNoteOpen(false);}} backLabel={{home:'返回学习首页',library:'返回书架',notes:'返回我的笔记',search:'返回搜索结果',study:'返回学习计划',review:'返回间隔复习',settings:'返回阅读偏好',reader:'返回书架'}[readerOrigin]} onBack={()=>void changePage(readerOrigin)} onOpen={id=>void openLesson(id)} onSaved={refreshNotes} flag={flags[current.id]} onFlag={(key,value)=>void setFlag(current.id,key,value)} preferences={preferences} onPreferences={updatePreferences} position={()=>positions.current.get(current.id)||null} onRead={captureRead} jump={jump} onAddQueue={()=>addQueue([current.id])} audioPosition={()=>audioId===current.id?player.current?.position()||0:positions.current.get(current.id)?.audio||0} onSource={source=>void openSource(source)}/>}
    {page==='notes'&&<NoteWorkspace lessons={lessons} selectedNote={selectedNote} onConsumed={()=>setSelectedNote(null)} onSource={source=>void openSource(source)} onChanged={refreshNotes}/>}
    {page==='study'&&<StudyPage lessons={lessons} onOpen={id=>void openLesson(id)}/>}
    {page==='review'&&<ReviewPage lessons={lessons} onSource={source=>void openSource(source)}/>}
    {page==='settings'&&<main className="settings-page page-scroll"><div className="page-heading"><div><div className="eyebrow">YOUR READING SPACE</div><h1>阅读偏好</h1><p>调整主题、排版与播放偏好。</p></div></div><div className="settings-card"><div><div><strong>阅读主题</strong><p>根据光线，选择舒适的阅读颜色。</p></div><button className="secondary-button" onClick={changeTheme}>{theme==='light'?<Sun size={17}/>:<Moon size={17}/>} {theme==='light'?'浅色主题':'深色主题'}</button></div><div><div><strong>主侧栏</strong><p>收起导航，给正文更多空间。</p></div><button className="secondary-button" onClick={()=>changeCollapsed(!collapsed)}>{collapsed?'展开侧栏':'收起侧栏'}</button></div><div><div><strong>默认播放速度</strong><p>下次打开时保留这个偏好。</p></div><select aria-label="默认播放速度" value={rate} onChange={e=>{const value=Number(e.target.value);setRate(value);void saveSetting('playbackRate',value);}}>{[.75,1,1.25,1.5,1.75,2].map(r=><option value={r} key={r}>{r}×</option>)}</select></div><div><div><strong>正文排版</strong><p>也可以在听读页调整；续学使用段落位置。</p></div><select aria-label="默认正文字号" value={preferences.fontSize} onChange={e=>updatePreferences({fontSize:Number(e.target.value)})}>{[16,18,20,22,24].map(n=><option key={n} value={n}>{n} 号</option>)}</select></div><div><div><strong>连续播放</strong><p>本讲结束后按播放队列继续；无音频条目不会加入队列。</p></div><label><input type="checkbox" aria-label="默认连续播放" checked={continuous} onChange={e=>{setContinuous(e.target.checked);void saveSetting('continuousPlay',e.target.checked);}}/>启用</label></div><div><div><strong>快捷键</strong><p>空格播放 / 暂停，← → 前后 15 秒；输入文字时不触发播放快捷键。</p></div><span>Ctrl+K 搜索 · Ctrl+F 文内查找</span></div></div><BackupPanel onPrepare={async()=>{snapshotReading();await flushNotes();await saveOpenPositions();}}/><div className="about-card"><img src="jyrk://app/brand.png" alt={appConfig.name}/><div><h2>{appConfig.name}</h2><p>收听课程、阅读文稿、记录笔记与安排复习。休眠恢复后点击播放继续。</p><span>应用 v{data.version} · 课程库 {data.contentVersion}</span></div></div></main>}
    </div><Player ref={player} onPlayingChange={value=>{setIsPlaying(value);if(value)void saveSetting('lastAudioLesson',audioIdRef.current);}} onOpenCurrent={()=>audioLesson&&void openLesson(audioLesson.id)} lesson={audioLesson} lessons={lessons} queue={queue} onQueue={updateQueue} onNavigate={(id,auto)=>selectAudio(id,auto)} continuous={continuous} onContinuous={value=>{setContinuous(value);void saveSetting('continuousPlay',value);}} rate={rate} onRate={value=>{setRate(value);void saveSetting('playbackRate',value);}} volume={volume} onVolume={value=>{setVolume(value);void saveSetting('volume',value);}} onPosition={captureAudio} onError={setError} autoplayRequest={autoplay} seekRequest={seekRequest}/><LearningTracker audioLessonId={audioLesson?.id||null} readingLessonId={current.id} reading={page==='reader'&&!!detail&&detail.id===current.id&&detail.textStatus!=='missing_body'} onError={setError}/>{toast&&<div role="status" className="toast">{toast}<button aria-label="关闭状态提示" onClick={()=>setToast('')}><X size={15}/></button></div>}</div>;
}
