const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const {temporaryDirectory}=require('./temporary.cjs');
const {loadLibrary,containedFile,validateId,parseRange}=require('../desktop/library.cjs');
const {openSearch}=require('../desktop/search.cjs');
let importLibrary,markdownBlocks;
test.before(async()=>({importLibrary,markdownBlocks}=await import('../scripts/import-library.mjs')));
function setup(label){const base=temporaryDirectory(label),input=path.join(base,'input'),output=path.join(base,'library');fs.mkdirSync(input);return {base,input,output,reportFile:path.join(base,'report.json'),libraryId:'test-library'};}
function put(input,name,data){const file=path.join(input,name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,data);}
function wav(){const b=Buffer.alloc(2044);b.write('RIFF');b.writeUInt32LE(2036,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(1000,24);b.writeUInt32LE(2000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(2000,40);return b;}
function catalog(output){return JSON.parse(fs.readFileSync(path.join(output,'catalog.json'),'utf8'));}
test('automatic import pairs separated folders, keeps text-only and audio-only lessons, and hashes resources',async()=>{const o=setup('import-pair');put(o.input,'音频/基础/01-入门.wav',wav());put(o.input,'文稿/基础/01-入门.md','# 入门\n\n学习问题与行动。');put(o.input,'文稿/基础/02-文稿.txt','仅文稿也可阅读。');put(o.input,'音频/基础/03-声音.wav',wav());const report=await importLibrary(o);assert.deepEqual(report.courses.map(c=>c.status),['paired','text-only','audio-only']);const lib=loadLibrary(o.output);assert.equal(lib.summaries.length,3);assert.equal(lib.catalog.lessons[0].audio.duration_seconds,1);assert.ok(lib.catalog.lessons[0].text.paragraphs.length);assert.equal(lib.catalog.lessons[2].text.status,'missing_body');const manifest=JSON.parse(fs.readFileSync(path.join(o.output,'resource-manifest.json')));for(const entry of manifest.files)assert.equal(fs.statSync(path.join(o.output,entry.path)).size,entry.bytes);});
test('dry run does not publish a library; explicit mapping resolves differently named files',async()=>{const o=setup('import-map');put(o.input,'audio/recording.wav',wav());put(o.input,'texts/lecture.md','# 我的课程');const mapping=path.join(o.base,'mapping.json');fs.writeFileSync(mapping,JSON.stringify({courses:[{id:'custom-first',title:'入门',group:'第九组',text:'texts/lecture.md',audio:'audio/recording.wav'}]}));await importLibrary({...o,mapping,dryRun:true});assert.equal(fs.existsSync(o.output),false);await importLibrary({...o,mapping});assert.equal(loadLibrary(o.output).get('custom-first').title,'入门');});
test('ambiguous pairs stop before overwriting the previous library',async()=>{const o=setup('import-conflict');put(o.input,'基础/01.md','原课程');await importLibrary(o);const before=fs.readFileSync(path.join(o.output,'catalog.json'));put(o.input,'基础/01.txt','同名文稿');await assert.rejects(importLibrary(o),/无法唯一配对/);assert.deepEqual(fs.readFileSync(path.join(o.output,'catalog.json')),before);assert.equal(JSON.parse(fs.readFileSync(o.reportFile)).ambiguous.length,1);});
test('inserted lessons and paragraphs preserve existing automatically generated IDs',async()=>{const o=setup('import-stable');put(o.input,'基础/02.md','原始段落甲。\n\n原始段落乙。');await importLibrary(o);const old=catalog(o.output).lessons[0];put(o.input,'基础/01.md','新课程。');put(o.input,'基础/02.md','新增在前面。\n\n原始段落甲。\n\n原始段落乙。');await importLibrary(o);const revised=catalog(o.output).lessons.find(l=>l.title==='02');assert.equal(revised.id,old.id);for(const block of old.text.paragraphs)assert.equal(revised.text.paragraphs.find(b=>b.text===block.text).block_id,block.block_id);});
test('seven groups and generic IDs work in the library and search filters',async()=>{const o=setup('import-groups');for(let i=1;i<=7;i++)put(o.input,'分组'+i+'/课程.md','共同搜索词：框架学习。');await importLibrary(o);const c=catalog(o.output);assert.equal(c.seasons.length,7);const index=path.join(o.base,'search.sqlite'),builder=path.resolve(__dirname,'../scripts/build-search.cjs');const result=spawnSync(process.execPath,[builder,path.join(o.output,'catalog.json'),index],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);const search=openSearch(index,path.join(o.output,'catalog.json'));try{const hits=search.search({query:'框架',scope:'body',season:7,page:0});assert.equal(hits.total,1);assert.equal(hits.results[0].season,7);}finally{search.close();}validateId('custom-course_2026');assert.throws(()=>validateId('../escape'));});
test('mapping escape, duplicate IDs and invalid UTF-8 preserve the existing library',async()=>{const o=setup('import-invalid');put(o.input,'good.md','原正文');await importLibrary(o);const before=fs.readFileSync(path.join(o.output,'catalog.json')),mapping=path.join(o.base,'mapping.json');put(o.base,'outside.md','外部文件');fs.writeFileSync(mapping,JSON.stringify({courses:[{id:'safe',text:'../outside.md'}]}));await assert.rejects(importLibrary({...o,mapping}),/相对路径/);fs.writeFileSync(mapping,JSON.stringify({courses:[{id:'same',text:'good.md'},{id:'same',text:'good.md'}]}));await assert.rejects(importLibrary({...o,mapping}),/ID 重复/);put(o.input,'bad.txt',Buffer.from([0xff,0xfe,0xff]));await assert.rejects(importLibrary(o),/encoded data/);assert.deepEqual(fs.readFileSync(path.join(o.output,'catalog.json')),before);assert.equal(fs.readdirSync(o.base).some(f=>f.startsWith('.library-stage-')),false);});
test('local document images are copied, external images are skipped, and missing images do not replace the library',async()=>{const o=setup('import-images');put(o.input,'lesson.md','正文。\n\n![插图](figure.png)\n\n![远程](https://example.com/a.png)');put(o.input,'figure.png',fs.readFileSync(path.resolve(__dirname,'../public/brand.png')));const result=await importLibrary(o);assert.equal(catalog(o.output).lessons[0].text.attachments.length,1);assert.equal(result.warnings.length,1);const before=fs.readFileSync(path.join(o.output,'catalog.json'));fs.unlinkSync(path.join(o.input,'figure.png'));await assert.rejects(importLibrary(o));assert.deepEqual(fs.readFileSync(path.join(o.output,'catalog.json')),before);});
test('markdown fences retain blank lines, and resource access rejects traversal while serving audio ranges',()=>{const blocks=markdownBlocks('```js\nconst x=1;\n\nconsole.log(x);\n```\n\n末段。','custom-id');assert.equal(blocks.length,2);assert.ok(blocks[0].text.includes('\n\n'));const o=setup('import-range');put(o.input,'one.txt','hello');assert.throws(()=>containedFile(o.input,'../outside.txt'));assert.throws(()=>containedFile(o.input,'C:/Windows/system.ini'));assert.deepEqual(parseRange('bytes=2-4',10),{start:2,end:4,partial:true});assert.equal(parseRange('bytes=10-20',10),null);});
