'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {randomUUID}=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const {openDatabase}=require('../desktop/database.cjs');
const {createBackup,prepareRestore,restoreBackup,sha}=require('../desktop/backup.cjs');
const {resolveAnnotation}=require('../desktop/anchors.cjs');
const {openSearch}=require('../desktop/search.cjs');
const root=path.resolve(__dirname,'../..'),catalogFile=path.join(root,'build/test-fixture/library/catalog.json'),catalog=JSON.parse(fs.readFileSync(catalogFile,'utf8')),contentHash=sha(fs.readFileSync(catalogFile));
const {temporaryDirectory,legacyDatabase}=require('./temporary.cjs');
function directory(label){return temporaryDirectory(label);}
const lesson=catalog.lessons.find(l=>l.id==='demo-intro'),block=lesson.text.paragraphs.find(b=>b.text.includes('框架自制'));
const annotation=()=>({lessonId:lesson.id,blockId:block.block_id,quote:'框架自制',start:0,end:4,prefix:'',suffix:'',comment:'留下一个行动。',color:'yellow',sourceSha:lesson.text.sha256});

test('synthetic legacy database migrates with a consistent pre-migration snapshot and preserves note IDs, Chinese drafts, flags and anchors',()=>{
  const previous=legacyDatabase();
  const target=directory('migration');fs.copyFileSync(previous,path.join(target,'learning.sqlite'));
  const before=new DatabaseSync(previous,{readOnly:true}),notes=before.prepare('SELECT id,lesson_id,content FROM notes').all(),positions=before.prepare('SELECT * FROM progress').all();before.close();
  const db=openDatabase(target);try{assert.equal(Object.values(db.raw.prepare('PRAGMA user_version').get())[0],3);for(const n of notes){assert.equal(db.note(n.lesson_id).id,n.id);assert.equal(db.note(n.lesson_id).content,n.content);}for(const p of positions){assert.equal(db.progress(p.lesson_id).read_anchor,p.read_anchor);assert.equal(db.progress(p.lesson_id).audio_position,p.audio_position);}const backups=fs.readdirSync(path.join(target,'backups'));assert.equal(backups.length,1);const old=new DatabaseSync(path.join(target,'backups',backups[0]),{readOnly:true});assert.equal(Object.values(old.prepare('PRAGMA user_version').get())[0],2);assert.deepEqual(old.prepare('SELECT id,lesson_id,content FROM notes').all(),notes);old.close();}finally{db.close();}
});
test('course, independent and excerpt notes preserve IDs, tags, source and trash recovery without losing attachments',()=>{
  const db=openDatabase(directory('notes'));try{const original=db.saveNote(lesson.id,'课程中的中文笔记。');const free=db.editNote({kind:'free',title:'长期主义',content:'云杉线索',tags:['实践','实践','阅读']});assert.deepEqual(free.tags,['实践','阅读']);const excerpt=db.editNote({kind:'excerpt',title:'课程摘录',content:'自己的理解',tags:[],sourceLesson:lesson.id,sourceBlock:block.block_id,sourceQuote:'框架自制'});assert.equal(excerpt.source_lesson,lesson.id);assert.equal(db.allNotes().length,3);db.trashNote(free.id);assert.equal(db.allNotes().length,2);assert.equal(db.allNotes(true)[0].id,free.id);db.trashNote(free.id,true);assert.equal(db.noteById(free.id).content,'云杉线索');db.saveNote(lesson.id,'');assert.equal(db.note(lesson.id),null);db.saveNote(lesson.id,'重新写一条笔记');assert.equal(db.note(lesson.id).id,original.id);assert.equal(db.flags().some(f=>f.lesson_id===null),false);}finally{db.close();}
});
test('annotations reanchor after paragraph IDs change and retain unresolved or ambiguous quotes and comments',()=>{
  const original={id:'a',block_id:'old',quote:'一个值得回忆的观点',comment:'原批注不会丢失'};
  const revised={blocks:[{id:'new',text:'这里新增了一句。一个值得回忆的观点，接着解释。'}]};const matched=resolveAnnotation(original,revised);assert.equal(matched.anchor_state,'reanchored');assert.equal(matched.resolved_block_id,'new');assert.equal(matched.comment,original.comment);
  const missing=resolveAnnotation(original,{blocks:[{id:'new',text:'原句已经删除'}]});assert.equal(missing.anchor_state,'orphaned');assert.equal(missing.quote,original.quote);assert.equal(missing.comment,original.comment);
  const ambiguous=resolveAnnotation(original,{blocks:[{id:'one',text:original.quote},{id:'two',text:original.quote}]});assert.equal(ambiguous.anchor_state,'orphaned');assert.equal(ambiguous.resolved_block_id,null);
});
test('review feedback changes due dates, records history, preserves sources and rejects paused or premature reviews',()=>{
  const db=openDatabase(directory('review'));try{let card=db.saveCard({question:'这个观点如何应用？',answer:'保留自己的回答。',lessonId:lesson.id,blockId:block.block_id,sourceQuote:'框架自制',dueDay:'2026-10-04'});card=db.rateCard(card.id,'good','2026-10-04');assert.equal(card.due_day,'2026-10-05');assert.equal(card.repetitions,1);assert.throws(()=>db.rateCard(card.id,'good','2026-10-04'));card=db.rateCard(card.id,'good','2026-10-05');assert.equal(card.interval_days,3);card=db.rateCard(card.id,'again','2026-10-08');assert.equal(card.interval_days,1);assert.equal(card.lapses,1);db.saveCard({id:card.id,question:'修改过的问题',answer:card.answer,dueDay:'2026-10-09',paused:true});assert.throws(()=>db.rateCard(card.id,'easy','2026-10-09'));const rows=db.raw.prepare('SELECT * FROM review_events ORDER BY reviewed_at').all();assert.equal(rows.length,3);assert.equal(rows[2].due_after,'2026-10-09');assert.equal(db.cards()[0].source_quote,'框架自制');}finally{db.close();}
});
test('learning samples are idempotent, union only actual heard intervals and keep simultaneous time separate from category totals',()=>{
  const db=openDatabase(directory('statistics'));try{const item={sessionId:'sample-session',sequence:0,lessonId:lesson.id,day:'2026-10-04',startedAt:'2026-10-04T06:00:00Z',audioSeconds:4,readSeconds:3,totalSeconds:5,intervals:[[0,2],[2,4]]};assert.equal(db.recordSample(item),true);assert.equal(db.recordSample(item),false);db.recordSample({...item,sequence:1,audioSeconds:2,readSeconds:0,totalSeconds:2,intervals:[[1,3]]});db.saveProgress(lesson.id,lesson.audio.duration_seconds,500,block.block_id,.5);const stats=db.studyData('2026-10-04');assert.equal(stats.days[0].total_seconds,7);assert.equal(stats.days[0].audio_seconds,6);assert.deepEqual(stats.coverage[0].intervals,[[0,4]]);assert.throws(()=>db.recordSample({...item,sequence:2,totalSeconds:2}));assert.throws(()=>db.recordSample({...item,sequence:2,totalSeconds:100}));}finally{db.close();}
});
test('actual-frame accounting excludes idle reading, seek jumps, buffering and suspend gaps while deduplicating simultaneous listening and reading',async()=>{
  const {compareFrames}=await import('../src/tracking.ts');const previous={time:1000,lessonId:lesson.id,position:20,rate:1,playing:true,seeking:false,seekSerial:0,reading:true,focused:true,visible:true,lastInteraction:1000};
  const current={...previous,time:2000,position:21};assert.deepEqual(compareFrames(previous,current),{audioSeconds:1,readSeconds:1,totalSeconds:1,intervals:[[20,21]]});assert.equal(compareFrames(previous,{...current,position:800,seekSerial:1}).audioSeconds,0);assert.equal(compareFrames(previous,{...current,time:62000}).totalSeconds,0);assert.equal(compareFrames({...previous,reading:false},{...current,reading:false,position:20}).totalSeconds,0);assert.equal(compareFrames({...previous,focused:false},{...current,focused:false}).totalSeconds,1);assert.equal(compareFrames({...previous,playing:false,time:70000},{...current,playing:false,time:71000,lastInteraction:1000}).totalSeconds,0);
});
test('full-text note search includes independent titles, tags and excerpts and excludes deleted notes supplied by the store',()=>{
  const db=openDatabase(directory('search')),search=openSearch(path.join(root,'build/test-fixture/search-v1.sqlite'),catalogFile);try{const note=db.editNote({kind:'free',title:'银杏叶',content:'与课程无关的独立想法。',tags:['云杉']});const hit=search.search({query:'云杉',scope:'notes',page:0,season:0},db.allNotes()).results[0];assert.equal(hit.noteId,note.id);assert.equal(hit.season,0);assert.equal(search.search({query:'银杏叶',scope:'notes',page:0,season:1},db.allNotes()).total,0);db.trashNote(note.id);assert.equal(search.search({query:'云杉',scope:'notes',page:0,season:0},db.allNotes()).total,0);}finally{search.close();db.close();}
});
function populate(db,target){
  db.set('theme','dark');db.set('dailyGoalMinutes',25);db.saveNote(lesson.id,'完整恢复的课程笔记');const free=db.editNote({kind:'free',title:'含图片的独立笔记',content:'完整恢复正文',tags:['备份']});db.addAnnotations([annotation()]);db.addBookmark({lessonId:lesson.id,kind:'audio',position:88,label:'声音书签'});const card=db.saveCard({question:'恢复后卡片还在吗？',answer:'还在。',lessonId:lesson.id,blockId:block.block_id,dueDay:'2026-10-04'});db.rateCard(card.id,'good','2026-10-04');db.recordSample({sessionId:'backup-statistics',sequence:0,lessonId:lesson.id,day:'2026-10-04',startedAt:'2026-10-04T06:00:00Z',audioSeconds:3,readSeconds:2,totalSeconds:3,intervals:[[80,83]]});db.savePlan({name:'恢复计划',lessonIds:[lesson.id,'demo-text'],dailyLimit:1,startDay:'2026-10-04'});db.saveProgress(lesson.id,88,40,block.block_id,.2);db.flag(lesson.id,'favorite',true);
  const image=fs.readFileSync(path.join(root,'app/public/brand.png')),fileName=sha(image)+'-1234abcd.png';fs.mkdirSync(path.join(target,'assets'));fs.writeFileSync(path.join(target,'assets',fileName),image);db.addAsset({noteId:free.id,name:'中文图片.png',fileName,sha256:sha(image),bytes:image.length});return free;
}
test('consistent SQLite and attachment backup restores all personal data in a fresh profile and makes a recoverable before-restore backup',async()=>{
  const source=directory('backup-source'),target=directory('backup-clean');let db=openDatabase(source),clean=openDatabase(target);const file=path.join(source,'personal.jyrk-backup');
  try{const free=populate(db,source);await createBackup(db,source,file,contentHash);const record=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(record.assets.length,1);assert.ok(fs.statSync(file).size<10*1024*1024);assert.equal(Object.hasOwn(record,'courses'),false);clean.editNote({kind:'free',title:'恢复之前的记录',content:'必须先备份',tags:[]});const result=await restoreBackup(file,target,contentHash,clean,openDatabase);clean=result.store;assert.equal(clean.note(lesson.id).content,'完整恢复的课程笔记');assert.equal(clean.noteById(free.id).tags[0],'备份');assert.equal(clean.progress(lesson.id).audio_position,88);assert.equal(clean.annotations(lesson.id).length,1);assert.equal(clean.bookmarks(lesson.id).length,1);assert.equal(clean.cards().length,1);assert.equal(clean.plans().length,1);assert.equal(clean.assets().length,1);for(const table of ['settings','notes','progress','course_flags','annotations','bookmarks','review_cards','review_events','plans','learning_samples','heard_coverage','personal_assets'])assert.deepEqual(clean.raw.prepare('SELECT * FROM '+table).all(),db.raw.prepare('SELECT * FROM '+table).all(),table+' logical contents survive backup');assert.equal(sha(fs.readFileSync(path.join(target,'assets',clean.assets()[0].file_name))),clean.assets()[0].sha256);assert.equal(prepareRestore(result.beforeRestore,target,contentHash).summary.notes,1);}finally{db.close();clean.close();}
});
test('invalid versions, missing attachments, damaged checksums and hostile attachment paths never replace current data',async()=>{
  const target=directory('invalid-backup');const db=openDatabase(target);try{populate(db,target);const file=path.join(target,'valid.jyrk-backup');await createBackup(db,target,file,contentHash);const original=JSON.parse(fs.readFileSync(file,'utf8'));
    for(const mutate of [r=>r.formatVersion=99,r=>r.databaseVersion=99,r=>r.contentHash='wrong',r=>r.database.sha256='0'.repeat(64),r=>r.assets=[],r=>r.assets[0].name='../escape.png',r=>r.assets[0].sha256='0'.repeat(64)]){
      const damaged=structuredClone(original);mutate(damaged);const bad=path.join(target,randomUUID()+'.jyrk-backup');fs.writeFileSync(bad,JSON.stringify(damaged));const before=db.allNotes().map(n=>({id:n.id,content:n.content}));assert.throws(()=>prepareRestore(bad,target,contentHash));assert.deepEqual(db.allNotes().map(n=>({id:n.id,content:n.content})),before);assert.equal(Object.values(db.raw.prepare('PRAGMA integrity_check').get())[0],'ok');
    }
  }finally{db.close();}
});
test('a failure during database replacement rolls back the original notes and assets and leaves the before-restore backup available',async()=>{
  const source=directory('rollback-source'),target=directory('rollback-target');const sourceDb=openDatabase(source);let current=openDatabase(target);try{populate(sourceDb,source);const file=path.join(source,'restore.jyrk-backup');await createBackup(sourceDb,source,file,contentHash);const old=current.editNote({kind:'free',title:'现有数据',content:'回滚后仍在',tags:[]});let attempts=0;await assert.rejects(async()=>{try{await restoreBackup(file,target,contentHash,current,dir=>{if(++attempts===1)throw new Error('Injected replacement failure');return openDatabase(dir);});}catch(error){current=error.recoveredStore;throw error;}},/Injected replacement failure/);assert.equal(current.noteById(old.id).content,'回滚后仍在');assert.ok(fs.readdirSync(path.join(target,'backups')).some(f=>f.startsWith('before-restore-')));assert.equal(current.cards().length,0);}finally{sourceDb.close();current.close();}
});
test('a backup with a valid checksum but an unexpected SQLite trigger is rejected before replacing current data',async()=>{
  const target=directory('invalid-schema'),db=openDatabase(target);try{db.editNote({kind:'free',title:'现有中文笔记',content:'结构错误时仍然保留。',tags:[]});const file=path.join(target,'safe.jyrk-backup');await createBackup(db,target,file,contentHash);const record=JSON.parse(fs.readFileSync(file,'utf8')),temp=path.join(target,'altered.sqlite');fs.writeFileSync(temp,Buffer.from(record.database.data,'base64'));const altered=new DatabaseSync(temp);altered.exec('CREATE TRIGGER unsupported AFTER INSERT ON notes BEGIN DELETE FROM progress; END;');altered.close();const bytes=fs.readFileSync(temp);record.database={bytes:bytes.length,sha256:sha(bytes),data:bytes.toString('base64')};const invalid=path.join(target,'unsupported.jyrk-backup');fs.writeFileSync(invalid,JSON.stringify(record));assert.throws(()=>prepareRestore(invalid,target,contentHash),/结构不受支持/);assert.equal(db.allNotes()[0].content,'结构错误时仍然保留。');}finally{db.close();}
});

test('parallel listening and reading preserve each course while deduplicating daily time',async()=>{
  const {compareCourseFrames}=await import('../src/tracking.ts');
  const previous={time:1000,audioLessonId:'demo-intro',readingLessonId:'demo-text',position:20,rate:1,playing:true,seeking:false,seekSerial:0,reading:true,focused:true,visible:true,lastInteraction:1000};
  const split=compareCourseFrames(previous,{...previous,time:2000,position:21});
  assert.deepEqual(split,[{lessonId:'demo-intro',audioSeconds:1,readSeconds:0,totalSeconds:1,intervals:[[20,21]]},{lessonId:'demo-text',audioSeconds:0,readSeconds:1,totalSeconds:1,intervals:[]}]);
  const changed=compareCourseFrames(previous,{...previous,time:2000,position:21,readingLessonId:'demo-advanced'});assert.equal(changed.length,1);assert.equal(changed[0].lessonId,'demo-intro');
  const db=openDatabase(directory('parallel-statistics'));try{
    for(let window=0;window<2;window++)for(let index=0;index<split.length;index++)db.recordSample({sessionId:'parallel-v1:accounting-test',sequence:window*2+index,day:'2026-10-04',startedAt:'2026-10-04T06:00:00Z',...split[index]});
    const stats=db.studyData('2026-10-04');assert.equal(stats.days[0].total_seconds,2);assert.equal(stats.days[0].audio_seconds,2);assert.equal(stats.days[0].read_seconds,2);assert.equal(stats.courses.find(c=>c.lesson_id==='demo-text').audio_seconds,0);assert.equal(stats.courses.find(c=>c.lesson_id==='demo-intro').read_seconds,0);assert.deepEqual(stats.coverage.map(c=>c.lesson_id),['demo-intro']);
  }finally{db.close();}
});
