import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath, pathToFileURL} from 'node:url';
const project=path.resolve(import.meta.dirname,'../..');
const config=JSON.parse(fs.readFileSync(path.join(project,'app/app.config.json'),'utf8'));
const textExtensions=new Set(['.md','.txt']), audioExtensions=new Set(['.mp3','.m4a','.wav','.ogg','.flac']);
const ignoredFolders=new Set(['audio','audios','text','texts','documents','音频','文稿','文字']);
const digest=value=>createHash('sha256').update(value).digest('hex');
const compare=(a,b)=>a.localeCompare(b,'zh-CN',{numeric:true});
async function hashFile(file){const h=createHash('sha256');for await(const chunk of fs.createReadStream(file))h.update(chunk);return h.digest('hex');}
function walk(directory,root=directory){const found=[];for(const entry of fs.readdirSync(directory,{withFileTypes:true})){const absolute=path.join(directory,entry.name);if(entry.isSymbolicLink())throw new Error('不接受文件或目录链接：'+path.relative(root,absolute));if(entry.isDirectory())found.push(...walk(absolute,root));else if(entry.isFile())found.push(path.relative(root,absolute).split(path.sep).join('/'));}return found.sort(compare);}
function sourceFile(root,relative,extensions){if(typeof relative!=='string'||!relative||path.isAbsolute(relative)||relative.split(/[\\/]/).includes('..'))throw new Error('资料路径必须是输入目录内的相对路径');const file=path.resolve(root,relative),real=fs.realpathSync(file),within=path.relative(root,real);if(!within||within.startsWith('..')||path.isAbsolute(within)||fs.lstatSync(file).isSymbolicLink()||!fs.statSync(real).isFile())throw new Error('资料路径越界或不是文件：'+relative);if(!extensions.has(path.extname(real).toLowerCase()))throw new Error('不支持的文件类型：'+relative);return real;}
export function markdownBlocks(markdown,id){const blocks=[],seen=new Map();let current=[],fence=null;const flush=()=>{const text=current.join('\n').trim();current=[];if(!text)return;const key=digest(text).slice(0,12),occurrence=(seen.get(key)||0)+1;seen.set(key,occurrence);blocks.push({block_id:`${id}-b${key}-${occurrence}`,order:blocks.length+1,text});};for(const line of markdown.replace(/\r\n?/g,'\n').split('\n')){const match=/^\s*(`{3,}|~{3,})/.exec(line);if(match){if(!fence)fence=match[1][0];else if(match[1][0]===fence)fence=null;}if(!line.trim()&&!fence)flush();else current.push(line);}flush();return blocks;}
function duration(file){if(path.extname(file).toLowerCase()==='.wav'){const fd=fs.openSync(file,'r');try{const b=Buffer.alloc(Math.min(fs.statSync(file).size,65536));fs.readSync(fd,b,0,b.length,0);if(b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WAVE'){let rate=0;for(let offset=12;offset+8<=b.length;){const kind=b.toString('ascii',offset,offset+4),size=b.readUInt32LE(offset+4);if(kind==='fmt '&&offset+20<=b.length)rate=b.readUInt32LE(offset+16);if(kind==='data'&&rate)return size/rate;offset+=8+size+(size%2);}}}finally{fs.closeSync(fd);}}const result=spawnSync('ffprobe',['-v','error','-show_entries','format=duration','-of','default=noprint_wrappers=1:nokey=1',file],{encoding:'utf8',timeout:15000,windowsHide:true});const value=Number(result.stdout?.trim());return result.status===0&&Number.isFinite(value)&&value>0?value:0;}
function automatic(files){const groups=new Map();for(const relative of files){const extension=path.extname(relative).toLowerCase();if(!textExtensions.has(extension)&&!audioExtensions.has(extension))continue;const segments=relative.split('/'),stem=path.basename(relative,extension).normalize('NFC'),folders=segments.slice(0,-1).filter(s=>!ignoredFolders.has(s.toLocaleLowerCase()));const group=folders.join(' / ')||'我的课程',key=group.normalize('NFC').toLocaleLowerCase()+'/'+stem.toLocaleLowerCase();const item=groups.get(key)||{key,title:stem,group,texts:[],audios:[]};item[textExtensions.has(extension)?'texts':'audios'].push(relative);groups.set(key,item);}return [...groups.values()].sort((a,b)=>compare(a.key,b.key));}
export async function importLibrary({input,output=path.join(project,'content-build/library'),mapping=null,dryRun=false,libraryId=config.libraryId,reportFile=path.join(project,'build/import-report.json')}={}){
 if(!input)throw new Error('请提供 --input 音频和文稿所在目录');
 if(typeof libraryId!=='string'||!/^[A-Za-z0-9][A-Za-z0-9._-]{0,100}$/.test(libraryId))throw new Error('libraryId 无效');
 const root=fs.realpathSync(path.resolve(input));if(!fs.statSync(root).isDirectory()||fs.lstatSync(path.resolve(input)).isSymbolicLink())throw new Error('输入必须是普通目录');
 output=path.resolve(output);if(output===root||output.startsWith(root+path.sep)||root.startsWith(output+path.sep))throw new Error('输入目录和输出课程库不能互相包含');
 const files=walk(root),items=mapping?JSON.parse(fs.readFileSync(path.resolve(mapping),'utf8')).courses:automatic(files);
 if(!Array.isArray(items)||!items.length)throw new Error('没有可导入的课程；支持 Markdown/TXT 和 MP3/M4A/WAV/OGG/FLAC');
 const report={libraryId,courses:[],ambiguous:[],unsupported:files.filter(f=>!textExtensions.has(path.extname(f).toLowerCase())&&!audioExtensions.has(path.extname(f).toLowerCase())&&!['.json','.png','.jpg','.jpeg','.webp'].includes(path.extname(f).toLowerCase())),warnings:[]};
 const records=items.map((item,index)=>{if(item.texts?.length>1||item.audios?.length>1)report.ambiguous.push({title:item.title,texts:item.texts,audios:item.audios});const text=item.text??item.texts?.[0]??null,audio=item.audio??item.audios?.[0]??null;if(!text&&!audio)throw new Error('课程必须有音频或文稿');const title=String(item.title||path.basename(text||audio,path.extname(text||audio))).trim();if(!title||title.length>300)throw new Error('课程标题无效');const group=String(item.group||'我的课程').trim();if(!group||group.length>100)throw new Error('课程分组无效');const id=item.id||'L'+digest(libraryId+':'+(item.key||group+'/'+path.basename(text||audio,path.extname(text||audio)).normalize('NFC').toLocaleLowerCase())).slice(0,24);if(!/^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/.test(id))throw new Error('课程 ID 无效：'+id);const textFile=text?sourceFile(root,text,textExtensions):null,audioFile=audio?sourceFile(root,audio,audioExtensions):null;report.courses.push({id,title,group,text,audio,status:text&&audio?'paired':text?'text-only':'audio-only'});return {id,title,group,textFile,audioFile,item,index};});
 if(new Set(records.map(x=>x.id)).size!==records.length)throw new Error('课程 ID 重复，请在匹配清单中区分');
 const writeReport=()=>{fs.mkdirSync(path.dirname(reportFile),{recursive:true});fs.writeFileSync(reportFile,JSON.stringify(report,null,2)+'\n');};writeReport();
 if(report.ambiguous.length)throw new Error('有同名资料无法唯一配对，已写入匹配报告；请使用 --mapping 明确指定，不会覆盖现有课程库');
 if(dryRun)return report;
 const parent=path.dirname(output);fs.mkdirSync(parent,{recursive:true});if(fs.existsSync(output)&&fs.lstatSync(output).isSymbolicLink())throw new Error('输出课程库不能是目录链接');
 const stage=fs.mkdtempSync(path.join(parent,'.library-stage-')),backup=output+'.previous-'+Date.now();const inventory=[],lessons=[];let movedOld=false,committed=false;
 const materialize=async(file,relative)=>{const destination=path.join(stage,relative);fs.mkdirSync(path.dirname(destination),{recursive:true});fs.copyFileSync(file,destination);const entry={path:relative,bytes:fs.statSync(destination).size,sha256:await hashFile(destination)};inventory.push(entry);return entry;};
 try{const names=[...new Set(records.map(r=>r.group))].sort(compare),seasons=names.map((name,index)=>({id:index+1,name}));
 for(const record of records){const {id,title,textFile,audioFile,item,group}=record,season=seasons.find(s=>s.name===group),markdown=textFile?new TextDecoder('utf-8',{fatal:true}).decode(fs.readFileSync(textFile)).replace(/^\uFEFF/,''):`# ${title}\n\n本课程仅提供音频，可以收听并记录笔记。\n`;
 const textPath=`texts/${id}.md`,destination=path.join(stage,textPath);fs.mkdirSync(path.dirname(destination),{recursive:true});fs.writeFileSync(destination,markdown);const textEntry={path:textPath,bytes:fs.statSync(destination).size,sha256:await hashFile(destination)};inventory.push(textEntry);const attachments=[];
 if(textFile)for(const match of markdown.matchAll(/!\[[^\]]*\]\(([^\s)]+)(?:\s+[^)]*)?\)/g)){const link=match[1];if(/^(https?:|data:|file:)/i.test(link)){report.warnings.push({id,message:'外部图片未导入：'+link});continue;}const candidate=path.resolve(path.dirname(textFile),decodeURIComponent(link)),relative=path.relative(root,candidate);const image=sourceFile(root,relative,new Set(['.png','.jpg','.jpeg','.webp']));const imagePath='images/'+(await hashFile(image))+path.extname(image).toLowerCase();if(!inventory.some(f=>f.path===imagePath))await materialize(image,imagePath);attachments.push({path:imagePath,width:0,height:0});}
 let audio=null;if(audioFile){const format=path.extname(audioFile).slice(1).toLowerCase(),audioPath=`audio/${id}.${format}`,entry=await materialize(audioFile,audioPath);const seconds=item.durationSeconds??duration(audioFile);if(!Number.isFinite(seconds)||seconds<0||seconds>604800)throw new Error('音频时长无效');if(!seconds)report.warnings.push({id,message:'导入时无法解析时长；播放器会在打开音频后读取。安装 ffprobe 可在导入时解析。'});audio={path:audioPath,format,duration_seconds:seconds,bytes:entry.bytes,sha256:entry.sha256};}
 const hasBody=!!textFile&&!!markdown.trim();lessons.push({id,season_id:season.id,season_name:season.name,order:lessons.filter(l=>l.season_id===season.id).length+1,title,author:item.author||config.author,published_date:item.date||'',date_verified:!!item.date,topic:item.topic||group,kind:item.kind||'lesson',text:{...textEntry,status:hasBody?'available':'missing_body',status_note:hasBody?'':textFile?'提供的文稿为空。':'本课程为纯音频，没有提供文稿。',paragraphs:markdownBlocks(markdown,id),attachments},audio});
 }
 const catalog={schema_version:1,library_id:libraryId,content_version:'1-'+digest(JSON.stringify(lessons)).slice(0,12),resource_root:'.',author:config.author,seasons,lessons};const catalogData=JSON.stringify(catalog,null,2)+'\n';fs.writeFileSync(path.join(stage,'catalog.json'),catalogData);
 const manifest={content_version:catalog.content_version,catalog_sha256:digest(catalogData),files:inventory};fs.writeFileSync(path.join(stage,'resource-manifest.json'),JSON.stringify(manifest,null,2)+'\n');
 if(fs.existsSync(output)){fs.renameSync(output,backup);movedOld=true;}fs.renameSync(stage,output);committed=true;
 fs.writeFileSync(path.join(parent,'resource-manifest.json'),JSON.stringify(manifest,null,2)+'\n');if(movedOld)fs.rmSync(backup,{recursive:true});writeReport();return report;
 }catch(error){if(!committed&&movedOld&&!fs.existsSync(output))fs.renameSync(backup,output);throw error;}finally{if(fs.existsSync(stage))fs.rmSync(stage,{recursive:true});}
}
if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href){const options={};for(let i=2;i<process.argv.length;i++){const arg=process.argv[i];if(arg==='--dry-run')options.dryRun=true;else if(['--input','--output','--mapping','--library-id','--report'].includes(arg)){const value=process.argv[++i];if(!value||value.startsWith('--'))throw new Error('缺少参数：'+arg);options[{'--input':'input','--output':'output','--mapping':'mapping','--library-id':'libraryId','--report':'reportFile'}[arg]]=value;}else throw new Error('未知参数：'+arg);}try{const report=await importLibrary(options);console.log(`匹配 ${report.courses.length} 门课程；报告：${options.reportFile||'build/import-report.json'}`);if(!options.dryRun&&(!options.output||path.resolve(options.output)===path.join(project,'content-build/library'))){const index=spawnSync(process.execPath,[path.join(project,'app/scripts/build-search.cjs')],{stdio:'inherit',windowsHide:true});if(index.status!==0)process.exitCode=1;}}catch(error){console.error(error.message);process.exitCode=1;}}
